// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module ShiftUnit(	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:33:7]
  input  [1:0]  io_in_eew,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:34:14]
  input  [63:0] io_in,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:34:14]
  input  [63:0] io_shamt,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:34:14]
  input         io_rot,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:34:14]
  input         io_shl,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:34:14]
  input         io_signed,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:34:14]
  input  [1:0]  io_rm,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:34:14]
  output [63:0] io_out,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:34:14]
  output [7:0]  io_round	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:34:14]
);

  wire [7:0]      _rotator_7_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25]
  wire [7:0]      _shifter_7_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
  wire            _shifter_7_io_round;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
  wire [7:0]      _rotator_6_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25]
  wire [7:0]      _shifter_6_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
  wire            _shifter_6_io_round;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
  wire [7:0]      _rotator_5_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25]
  wire [7:0]      _shifter_5_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
  wire            _shifter_5_io_round;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
  wire [7:0]      _rotator_4_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25]
  wire [7:0]      _shifter_4_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
  wire            _shifter_4_io_round;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
  wire [15:0]     _rotator_3_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25]
  wire [15:0]     _shifter_3_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
  wire            _shifter_3_io_round;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
  wire [15:0]     _rotator_2_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25]
  wire [15:0]     _shifter_2_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
  wire            _shifter_2_io_round;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
  wire [31:0]     _rotator_1_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25]
  wire [31:0]     _shifter_1_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
  wire            _shifter_1_io_round;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
  wire [63:0]     _rotator_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25]
  wire [63:0]     _shifter_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
  wire            _shifter_io_round;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
  wire [3:0][5:0] _GEN = {6'h3F, 6'h1F, 6'hF, 6'h7};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28]
  wire            _shifter_io_sign_T_53 = io_in_eew == 2'h0;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32, :72:19]
  wire            _shifter_io_sign_T_38 = io_in_eew == 2'h1;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32]
  wire            _shifter_io_sign_T_20 = io_in_eew == 2'h2;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32]
  wire [6:0]      _GEN_0 = {1'h0, ((_shifter_io_sign_T_53 ? io_shamt[5:0] : 6'h0) | (_shifter_io_sign_T_38 ? io_shamt[5:0] : 6'h0) | (_shifter_io_sign_T_20 ? io_shamt[5:0] : 6'h0) | ((&io_in_eew) ? io_shamt[5:0] : 6'h0)) & _GEN[io_in_eew]};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32, :62:28, :63:51, :64:22, src/main/scala/chisel3/util/Mux.scala:30:73]
  wire [6:0]      _rotator_io_shamt_T_21 = 7'h8 << io_in_eew;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:65:30]
  wire [63:0]     _shift_out_3_0_T = io_rot ? _rotator_io_out : 64'h0;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25, :75:48, src/main/scala/chisel3/util/Mux.scala:30:73]
  wire [5:0]      _GEN_1 = ((_shifter_io_sign_T_53 ? io_shamt[13:8] : 6'h0) | (_shifter_io_sign_T_38 ? io_shamt[21:16] : 6'h0) | (_shifter_io_sign_T_20 ? io_shamt[37:32] : 6'h0)) & _GEN[io_in_eew];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32, :62:28, :63:51, src/main/scala/chisel3/util/Mux.scala:30:73]
  wire [31:0]     _shift_out_2_1_T = io_rot ? _rotator_1_io_out : 32'h0;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25, :75:48, src/main/scala/chisel3/util/Mux.scala:30:73]
  wire [4:0]      _GEN_2 = ((_shifter_io_sign_T_53 ? io_shamt[20:16] : 5'h0) | (_shifter_io_sign_T_38 ? io_shamt[36:32] : 5'h0)) & _GEN[io_in_eew][4:0];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32, :62:28, :63:51, :65:30, src/main/scala/chisel3/util/Mux.scala:30:73]
  wire [15:0]     _shift_out_1_2_T = io_rot ? _rotator_2_io_out : 16'h0;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25, :75:48, src/main/scala/chisel3/util/Mux.scala:30:73]
  wire [4:0]      _GEN_3 = ((_shifter_io_sign_T_53 ? io_shamt[28:24] : 5'h0) | (_shifter_io_sign_T_38 ? io_shamt[52:48] : 5'h0)) & _GEN[io_in_eew][4:0];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32, :62:28, :63:51, :65:30, src/main/scala/chisel3/util/Mux.scala:30:73]
  wire [15:0]     _shift_out_1_3_T = io_rot ? _rotator_3_io_out : 16'h0;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25, :75:48, src/main/scala/chisel3/util/Mux.scala:30:73]
  wire [3:0]      _GEN_4 = io_shamt[35:32] & _GEN[io_in_eew][3:0];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28, :63:51]
  wire [3:0]      _GEN_5 = io_shamt[43:40] & _GEN[io_in_eew][3:0];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28, :63:51]
  wire [3:0]      _GEN_6 = io_shamt[51:48] & _GEN[io_in_eew][3:0];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28, :63:51]
  wire [3:0]      _GEN_7 = io_shamt[59:56] & _GEN[io_in_eew][3:0];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28, :63:51]
  ShiftBlock shifter (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
    .io_in    ((_shifter_io_sign_T_53 ? {{56{io_signed & io_in[7]}}, io_in[7:0]} : 64'h0) | (_shifter_io_sign_T_38 ? {{48{io_signed & io_in[15]}}, io_in[15:0]} : 64'h0) | (_shifter_io_sign_T_20 ? {{32{io_signed & io_in[31]}}, io_in[31:0]} : 64'h0) | ((&io_in_eew) ? io_in : 64'h0)),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:52:{87,92,128}, :59:{32,57}, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_shamt (_GEN_0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:64:22]
    .io_shl   (io_shl),
    .io_sign  (io_signed & (_shifter_io_sign_T_53 & io_in[7] | _shifter_io_sign_T_38 & io_in[15] | _shifter_io_sign_T_20 & io_in[31] | (&io_in_eew) & io_in[63])),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32, :68:34, :69:48, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_rm    (io_rm),
    .io_out   (_shifter_io_out),
    .io_round (_shifter_io_round)
  );
  ShiftBlock rotator (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25]
    .io_in    ({32'h0, {16'h0, {8'h0, _shifter_io_sign_T_53 ? io_in[7:0] : 8'h0} | (_shifter_io_sign_T_38 ? io_in[15:0] : 16'h0)} | (_shifter_io_sign_T_20 ? io_in[31:0] : 32'h0)} | ((&io_in_eew) ? io_in : 64'h0)),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:{32,57}, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_shamt (_rotator_io_shamt_T_21 - _GEN_0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28, :64:22, :65:{30,44}]
    .io_shl   (~io_shl),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:67:23]
    .io_sign  (1'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32]
    .io_rm    (2'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:72:19]
    .io_out   (_rotator_io_out),
    .io_round (/* unused */)
  );
  ShiftBlock_2 shifter_1 (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
    .io_in    ((_shifter_io_sign_T_53 ? {{24{io_signed & io_in[15]}}, io_in[15:8]} : 32'h0) | (_shifter_io_sign_T_38 ? {{16{io_signed & io_in[31]}}, io_in[31:16]} : 32'h0) | (_shifter_io_sign_T_20 ? io_in[63:32] : 32'h0)),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:52:{87,92,128}, :59:{32,57}, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_shamt (_GEN_1),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28]
    .io_shl   (io_shl),
    .io_sign  (io_signed & (_shifter_io_sign_T_53 & io_in[15] | _shifter_io_sign_T_38 & io_in[31] | _shifter_io_sign_T_20 & io_in[63])),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32, :68:34, :69:48, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_rm    (io_rm),
    .io_out   (_shifter_1_io_out),
    .io_round (_shifter_1_io_round)
  );
  ShiftBlock_2 rotator_1 (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25]
    .io_in    ({16'h0, {8'h0, _shifter_io_sign_T_53 ? io_in[15:8] : 8'h0} | (_shifter_io_sign_T_38 ? io_in[31:16] : 16'h0)} | (_shifter_io_sign_T_20 ? io_in[63:32] : 32'h0)),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:{32,57}, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_shamt (_rotator_io_shamt_T_21[5:0] - _GEN_1),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28, :65:{30,44}]
    .io_shl   (~io_shl),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:67:23]
    .io_sign  (1'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32]
    .io_rm    (2'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:72:19]
    .io_out   (_rotator_1_io_out),
    .io_round (/* unused */)
  );
  ShiftBlock_4 shifter_2 (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
    .io_in    ((_shifter_io_sign_T_53 ? {{8{io_signed & io_in[23]}}, io_in[23:16]} : 16'h0) | (_shifter_io_sign_T_38 ? io_in[47:32] : 16'h0)),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:52:{87,92,128}, :59:{32,57}, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_shamt (_GEN_2),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28]
    .io_shl   (io_shl),
    .io_sign  (io_signed & (_shifter_io_sign_T_53 & io_in[23] | _shifter_io_sign_T_38 & io_in[47])),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32, :68:34, :69:48, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_rm    (io_rm),
    .io_out   (_shifter_2_io_out),
    .io_round (_shifter_2_io_round)
  );
  ShiftBlock_4 rotator_2 (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25]
    .io_in    ({8'h0, _shifter_io_sign_T_53 ? io_in[23:16] : 8'h0} | (_shifter_io_sign_T_38 ? io_in[47:32] : 16'h0)),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:{32,57}, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_shamt (_rotator_io_shamt_T_21[4:0] - _GEN_2),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28, :65:{30,44}]
    .io_shl   (~io_shl),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:67:23]
    .io_sign  (1'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32]
    .io_rm    (2'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:72:19]
    .io_out   (_rotator_2_io_out),
    .io_round (/* unused */)
  );
  ShiftBlock_4 shifter_3 (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
    .io_in    ((_shifter_io_sign_T_53 ? {{8{io_signed & io_in[31]}}, io_in[31:24]} : 16'h0) | (_shifter_io_sign_T_38 ? io_in[63:48] : 16'h0)),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:52:{87,92,128}, :59:{32,57}, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_shamt (_GEN_3),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28]
    .io_shl   (io_shl),
    .io_sign  (io_signed & (_shifter_io_sign_T_53 & io_in[31] | _shifter_io_sign_T_38 & io_in[63])),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32, :68:34, :69:48, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_rm    (io_rm),
    .io_out   (_shifter_3_io_out),
    .io_round (_shifter_3_io_round)
  );
  ShiftBlock_4 rotator_3 (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25]
    .io_in    ({8'h0, _shifter_io_sign_T_53 ? io_in[31:24] : 8'h0} | (_shifter_io_sign_T_38 ? io_in[63:48] : 16'h0)),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:{32,57}, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_shamt (_rotator_io_shamt_T_21[4:0] - _GEN_3),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28, :65:{30,44}]
    .io_shl   (~io_shl),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:67:23]
    .io_sign  (1'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32]
    .io_rm    (2'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:72:19]
    .io_out   (_rotator_3_io_out),
    .io_round (/* unused */)
  );
  ShiftBlock_8 shifter_4 (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
    .io_in    (io_in[39:32]),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:57]
    .io_shamt (_GEN_4),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28]
    .io_shl   (io_shl),
    .io_sign  (io_signed & io_in[39]),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:68:34, :69:48]
    .io_rm    (io_rm),
    .io_out   (_shifter_4_io_out),
    .io_round (_shifter_4_io_round)
  );
  ShiftBlock_8 rotator_4 (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25]
    .io_in    (io_in[39:32]),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:57]
    .io_shamt (_rotator_io_shamt_T_21[3:0] - _GEN_4),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28, :65:{30,44}]
    .io_shl   (~io_shl),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:67:23]
    .io_sign  (1'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32]
    .io_rm    (2'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:72:19]
    .io_out   (_rotator_4_io_out),
    .io_round (/* unused */)
  );
  ShiftBlock_8 shifter_5 (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
    .io_in    (io_in[47:40]),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:57]
    .io_shamt (_GEN_5),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28]
    .io_shl   (io_shl),
    .io_sign  (io_signed & io_in[47]),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:68:34, :69:48]
    .io_rm    (io_rm),
    .io_out   (_shifter_5_io_out),
    .io_round (_shifter_5_io_round)
  );
  ShiftBlock_8 rotator_5 (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25]
    .io_in    (io_in[47:40]),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:57]
    .io_shamt (_rotator_io_shamt_T_21[3:0] - _GEN_5),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28, :65:{30,44}]
    .io_shl   (~io_shl),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:67:23]
    .io_sign  (1'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32]
    .io_rm    (2'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:72:19]
    .io_out   (_rotator_5_io_out),
    .io_round (/* unused */)
  );
  ShiftBlock_8 shifter_6 (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
    .io_in    (io_in[55:48]),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:57]
    .io_shamt (_GEN_6),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28]
    .io_shl   (io_shl),
    .io_sign  (io_signed & io_in[55]),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:68:34, :69:48]
    .io_rm    (io_rm),
    .io_out   (_shifter_6_io_out),
    .io_round (_shifter_6_io_round)
  );
  ShiftBlock_8 rotator_6 (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25]
    .io_in    (io_in[55:48]),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:57]
    .io_shamt (_rotator_io_shamt_T_21[3:0] - _GEN_6),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28, :65:{30,44}]
    .io_shl   (~io_shl),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:67:23]
    .io_sign  (1'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32]
    .io_rm    (2'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:72:19]
    .io_out   (_rotator_6_io_out),
    .io_round (/* unused */)
  );
  ShiftBlock_8 shifter_7 (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:56:25]
    .io_in    (io_in[63:56]),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:57]
    .io_shamt (_GEN_7),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28]
    .io_shl   (io_shl),
    .io_sign  (io_signed & io_in[63]),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:68:34, :69:48]
    .io_rm    (io_rm),
    .io_out   (_shifter_7_io_out),
    .io_round (_shifter_7_io_round)
  );
  ShiftBlock_8 rotator_7 (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:57:25]
    .io_in    (io_in[63:56]),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:57]
    .io_shamt (_rotator_io_shamt_T_21[3:0] - _GEN_7),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:62:28, :65:{30,44}]
    .io_shl   (~io_shl),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:67:23]
    .io_sign  (1'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:59:32]
    .io_rm    (2'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:72:19]
    .io_out   (_rotator_7_io_out),
    .io_round (/* unused */)
  );
  assign io_out = (io_in_eew == 2'h0 ? {_shifter_7_io_out | (io_rot ? _rotator_7_io_out : 8'h0), _shifter_6_io_out | (io_rot ? _rotator_6_io_out : 8'h0), _shifter_5_io_out | (io_rot ? _rotator_5_io_out : 8'h0), _shifter_4_io_out | (io_rot ? _rotator_4_io_out : 8'h0), _shifter_3_io_out[7:0] | _shift_out_1_3_T[7:0], _shifter_2_io_out[7:0] | _shift_out_1_2_T[7:0], _shifter_1_io_out[7:0] | _shift_out_2_1_T[7:0], _shifter_io_out[7:0] | _shift_out_3_0_T[7:0]} : 64'h0) | (io_in_eew == 2'h1 ? {_shifter_3_io_out | _shift_out_1_3_T, _shifter_2_io_out | _shift_out_1_2_T, _shifter_1_io_out[15:0] | _shift_out_2_1_T[15:0], _shifter_io_out[15:0] | _shift_out_3_0_T[15:0]} : 64'h0) | (io_in_eew == 2'h2 ? {_shifter_1_io_out | _shift_out_2_1_T, _shifter_io_out[31:0] | _shift_out_3_0_T[31:0]} : 64'h0) | ((&io_in_eew) ? _shifter_io_out | _shift_out_3_0_T : 64'h0);	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:33:7, :56:25, :57:25, :59:32, :72:19, :75:{43,48}, :79:58, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
  assign io_round = (io_in_eew == 2'h0 ? {_shifter_7_io_round, _shifter_6_io_round, _shifter_5_io_round, _shifter_4_io_round, _shifter_3_io_round, _shifter_2_io_round, _shifter_1_io_round, _shifter_io_round} : 8'h0) | (io_in_eew == 2'h1 ? {1'h0, _shifter_3_io_round, 1'h0, _shifter_2_io_round, 1'h0, _shifter_1_io_round, 1'h0, _shifter_io_round} : 8'h0) | (io_in_eew == 2'h2 ? {3'h0, _shifter_1_io_round, 3'h0, _shifter_io_round} : 8'h0) | ((&io_in_eew) ? {7'h0, _shifter_io_round} : 8'h0);	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:33:7, :56:25, :59:32, :65:30, :72:19, :76:25, :80:58, src/main/scala/chisel3/util/Mux.scala:30:73, :32:36]
endmodule

