// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module VectorSMul(	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:238:7]
  input  [1:0]   io_eew,	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:239:14]
  input  [1:0]   io_vxrm,	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:239:14]
  input  [255:0] io_mul_in,	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:239:14]
  output [127:0] io_clipped,	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:239:14]
  output [15:0]  io_sat	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:239:14]
);

  wire              _GEN = io_vxrm != 2'h1;	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106]
  wire              _GEN_0 = io_vxrm != 2'h2;	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106]
  wire [8:0]        _smul_T_3 = io_mul_in[15:7] + {8'h0, (&io_vxrm) ? ~(io_mul_in[7]) & (|(io_mul_in[6:0])) : _GEN_0 & (_GEN | (|(io_mul_in[5:0])) | io_mul_in[7]) & io_mul_in[6]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [8:0]        _smul_T_8 = io_mul_in[31:23] + {8'h0, (&io_vxrm) ? ~(io_mul_in[23]) & (|(io_mul_in[22:16])) : _GEN_0 & (_GEN | (|(io_mul_in[21:16])) | io_mul_in[23]) & io_mul_in[22]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [8:0]        _smul_T_13 = io_mul_in[47:39] + {8'h0, (&io_vxrm) ? ~(io_mul_in[39]) & (|(io_mul_in[38:32])) : _GEN_0 & (_GEN | (|(io_mul_in[37:32])) | io_mul_in[39]) & io_mul_in[38]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [8:0]        _smul_T_18 = io_mul_in[63:55] + {8'h0, (&io_vxrm) ? ~(io_mul_in[55]) & (|(io_mul_in[54:48])) : _GEN_0 & (_GEN | (|(io_mul_in[53:48])) | io_mul_in[55]) & io_mul_in[54]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [8:0]        _smul_T_23 = io_mul_in[79:71] + {8'h0, (&io_vxrm) ? ~(io_mul_in[71]) & (|(io_mul_in[70:64])) : _GEN_0 & (_GEN | (|(io_mul_in[69:64])) | io_mul_in[71]) & io_mul_in[70]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [8:0]        _smul_T_28 = io_mul_in[95:87] + {8'h0, (&io_vxrm) ? ~(io_mul_in[87]) & (|(io_mul_in[86:80])) : _GEN_0 & (_GEN | (|(io_mul_in[85:80])) | io_mul_in[87]) & io_mul_in[86]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [8:0]        _smul_T_33 = io_mul_in[111:103] + {8'h0, (&io_vxrm) ? ~(io_mul_in[103]) & (|(io_mul_in[102:96])) : _GEN_0 & (_GEN | (|(io_mul_in[101:96])) | io_mul_in[103]) & io_mul_in[102]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [8:0]        _smul_T_38 = io_mul_in[127:119] + {8'h0, (&io_vxrm) ? ~(io_mul_in[119]) & (|(io_mul_in[118:112])) : _GEN_0 & (_GEN | (|(io_mul_in[117:112])) | io_mul_in[119]) & io_mul_in[118]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [8:0]        _smul_T_43 = io_mul_in[143:135] + {8'h0, (&io_vxrm) ? ~(io_mul_in[135]) & (|(io_mul_in[134:128])) : _GEN_0 & (_GEN | (|(io_mul_in[133:128])) | io_mul_in[135]) & io_mul_in[134]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [8:0]        _smul_T_48 = io_mul_in[159:151] + {8'h0, (&io_vxrm) ? ~(io_mul_in[151]) & (|(io_mul_in[150:144])) : _GEN_0 & (_GEN | (|(io_mul_in[149:144])) | io_mul_in[151]) & io_mul_in[150]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [8:0]        _smul_T_53 = io_mul_in[175:167] + {8'h0, (&io_vxrm) ? ~(io_mul_in[167]) & (|(io_mul_in[166:160])) : _GEN_0 & (_GEN | (|(io_mul_in[165:160])) | io_mul_in[167]) & io_mul_in[166]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [8:0]        _smul_T_58 = io_mul_in[191:183] + {8'h0, (&io_vxrm) ? ~(io_mul_in[183]) & (|(io_mul_in[182:176])) : _GEN_0 & (_GEN | (|(io_mul_in[181:176])) | io_mul_in[183]) & io_mul_in[182]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [8:0]        _smul_T_63 = io_mul_in[207:199] + {8'h0, (&io_vxrm) ? ~(io_mul_in[199]) & (|(io_mul_in[198:192])) : _GEN_0 & (_GEN | (|(io_mul_in[197:192])) | io_mul_in[199]) & io_mul_in[198]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [8:0]        _smul_T_68 = io_mul_in[223:215] + {8'h0, (&io_vxrm) ? ~(io_mul_in[215]) & (|(io_mul_in[214:208])) : _GEN_0 & (_GEN | (|(io_mul_in[213:208])) | io_mul_in[215]) & io_mul_in[214]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [8:0]        _smul_T_73 = io_mul_in[239:231] + {8'h0, (&io_vxrm) ? ~(io_mul_in[231]) & (|(io_mul_in[230:224])) : _GEN_0 & (_GEN | (|(io_mul_in[229:224])) | io_mul_in[231]) & io_mul_in[230]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [8:0]        _smul_T_78 = io_mul_in[255:247] + {8'h0, (&io_vxrm) ? ~(io_mul_in[247]) & (|(io_mul_in[246:240])) : _GEN_0 & (_GEN | (|(io_mul_in[245:240])) | io_mul_in[247]) & io_mul_in[246]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire              clip_hi_0 = $signed(_smul_T_3) > 9'sh7F;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_1 = $signed(_smul_T_8) > 9'sh7F;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_2 = $signed(_smul_T_13) > 9'sh7F;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_3 = $signed(_smul_T_18) > 9'sh7F;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_4 = $signed(_smul_T_23) > 9'sh7F;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_5 = $signed(_smul_T_28) > 9'sh7F;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_6 = $signed(_smul_T_33) > 9'sh7F;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_7 = $signed(_smul_T_38) > 9'sh7F;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_8 = $signed(_smul_T_43) > 9'sh7F;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_9 = $signed(_smul_T_48) > 9'sh7F;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_10 = $signed(_smul_T_53) > 9'sh7F;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_11 = $signed(_smul_T_58) > 9'sh7F;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_12 = $signed(_smul_T_63) > 9'sh7F;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_13 = $signed(_smul_T_68) > 9'sh7F;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_14 = $signed(_smul_T_73) > 9'sh7F;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_15 = $signed(_smul_T_78) > 9'sh7F;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_lo_0 = $signed(_smul_T_3) < -9'sh80;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_1 = $signed(_smul_T_8) < -9'sh80;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_2 = $signed(_smul_T_13) < -9'sh80;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_3 = $signed(_smul_T_18) < -9'sh80;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_4 = $signed(_smul_T_23) < -9'sh80;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_5 = $signed(_smul_T_28) < -9'sh80;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_6 = $signed(_smul_T_33) < -9'sh80;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_7 = $signed(_smul_T_38) < -9'sh80;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_8 = $signed(_smul_T_43) < -9'sh80;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_9 = $signed(_smul_T_48) < -9'sh80;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_10 = $signed(_smul_T_53) < -9'sh80;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_11 = $signed(_smul_T_58) < -9'sh80;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_12 = $signed(_smul_T_63) < -9'sh80;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_13 = $signed(_smul_T_68) < -9'sh80;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_14 = $signed(_smul_T_73) < -9'sh80;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_15 = $signed(_smul_T_78) < -9'sh80;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire [16:0]       _smul_T_83 = io_mul_in[31:15] + {16'h0, (&io_vxrm) ? ~(io_mul_in[15]) & (|(io_mul_in[14:0])) : _GEN_0 & (_GEN | (|(io_mul_in[13:0])) | io_mul_in[15]) & io_mul_in[14]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [16:0]       _smul_T_88 = io_mul_in[63:47] + {16'h0, (&io_vxrm) ? ~(io_mul_in[47]) & (|(io_mul_in[46:32])) : _GEN_0 & (_GEN | (|(io_mul_in[45:32])) | io_mul_in[47]) & io_mul_in[46]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [16:0]       _smul_T_93 = io_mul_in[95:79] + {16'h0, (&io_vxrm) ? ~(io_mul_in[79]) & (|(io_mul_in[78:64])) : _GEN_0 & (_GEN | (|(io_mul_in[77:64])) | io_mul_in[79]) & io_mul_in[78]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [16:0]       _smul_T_98 = io_mul_in[127:111] + {16'h0, (&io_vxrm) ? ~(io_mul_in[111]) & (|(io_mul_in[110:96])) : _GEN_0 & (_GEN | (|(io_mul_in[109:96])) | io_mul_in[111]) & io_mul_in[110]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [16:0]       _smul_T_103 = io_mul_in[159:143] + {16'h0, (&io_vxrm) ? ~(io_mul_in[143]) & (|(io_mul_in[142:128])) : _GEN_0 & (_GEN | (|(io_mul_in[141:128])) | io_mul_in[143]) & io_mul_in[142]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [16:0]       _smul_T_108 = io_mul_in[191:175] + {16'h0, (&io_vxrm) ? ~(io_mul_in[175]) & (|(io_mul_in[174:160])) : _GEN_0 & (_GEN | (|(io_mul_in[173:160])) | io_mul_in[175]) & io_mul_in[174]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [16:0]       _smul_T_113 = io_mul_in[223:207] + {16'h0, (&io_vxrm) ? ~(io_mul_in[207]) & (|(io_mul_in[206:192])) : _GEN_0 & (_GEN | (|(io_mul_in[205:192])) | io_mul_in[207]) & io_mul_in[206]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [16:0]       _smul_T_118 = io_mul_in[255:239] + {16'h0, (&io_vxrm) ? ~(io_mul_in[239]) & (|(io_mul_in[238:224])) : _GEN_0 & (_GEN | (|(io_mul_in[237:224])) | io_mul_in[239]) & io_mul_in[238]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire              clip_hi_0_1 = $signed(_smul_T_83) > 17'sh7FFF;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_1_1 = $signed(_smul_T_88) > 17'sh7FFF;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_2_1 = $signed(_smul_T_93) > 17'sh7FFF;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_3_1 = $signed(_smul_T_98) > 17'sh7FFF;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_4_1 = $signed(_smul_T_103) > 17'sh7FFF;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_5_1 = $signed(_smul_T_108) > 17'sh7FFF;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_6_1 = $signed(_smul_T_113) > 17'sh7FFF;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_7_1 = $signed(_smul_T_118) > 17'sh7FFF;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_lo_0_1 = $signed(_smul_T_83) < -17'sh8000;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_1_1 = $signed(_smul_T_88) < -17'sh8000;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_2_1 = $signed(_smul_T_93) < -17'sh8000;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_3_1 = $signed(_smul_T_98) < -17'sh8000;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_4_1 = $signed(_smul_T_103) < -17'sh8000;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_5_1 = $signed(_smul_T_108) < -17'sh8000;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_6_1 = $signed(_smul_T_113) < -17'sh8000;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_7_1 = $signed(_smul_T_118) < -17'sh8000;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire [32:0]       _smul_T_123 = io_mul_in[63:31] + {32'h0, (&io_vxrm) ? ~(io_mul_in[31]) & (|(io_mul_in[30:0])) : _GEN_0 & (_GEN | (|(io_mul_in[29:0])) | io_mul_in[31]) & io_mul_in[30]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [32:0]       _smul_T_128 = io_mul_in[127:95] + {32'h0, (&io_vxrm) ? ~(io_mul_in[95]) & (|(io_mul_in[94:64])) : _GEN_0 & (_GEN | (|(io_mul_in[93:64])) | io_mul_in[95]) & io_mul_in[94]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [32:0]       _smul_T_133 = io_mul_in[191:159] + {32'h0, (&io_vxrm) ? ~(io_mul_in[159]) & (|(io_mul_in[158:128])) : _GEN_0 & (_GEN | (|(io_mul_in[157:128])) | io_mul_in[159]) & io_mul_in[158]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire [32:0]       _smul_T_138 = io_mul_in[255:223] + {32'h0, (&io_vxrm) ? ~(io_mul_in[223]) & (|(io_mul_in[222:192])) : _GEN_0 & (_GEN | (|(io_mul_in[221:192])) | io_mul_in[223]) & io_mul_in[222]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}, :261:21]
  wire              clip_hi_0_2 = $signed(_smul_T_123) > 33'sh7FFFFFFF;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_1_2 = $signed(_smul_T_128) > 33'sh7FFFFFFF;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_2_2 = $signed(_smul_T_133) > 33'sh7FFFFFFF;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_3_2 = $signed(_smul_T_138) > 33'sh7FFFFFFF;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_lo_0_2 = $signed(_smul_T_123) < -33'sh80000000;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_1_2 = $signed(_smul_T_128) < -33'sh80000000;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_2_2 = $signed(_smul_T_133) < -33'sh80000000;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_3_2 = $signed(_smul_T_138) < -33'sh80000000;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire [64:0]       _smul_T_143 = io_mul_in[127:63] + {64'h0, (&io_vxrm) ? ~(io_mul_in[63]) & (|(io_mul_in[62:0])) : _GEN_0 & (_GEN | (|(io_mul_in[61:0])) | io_mul_in[63]) & io_mul_in[62]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}]
  wire [64:0]       _smul_T_148 = io_mul_in[255:191] + {64'h0, (&io_vxrm) ? ~(io_mul_in[191]) & (|(io_mul_in[190:128])) : _GEN_0 & (_GEN | (|(io_mul_in[189:128])) | io_mul_in[191]) & io_mul_in[190]};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:35, :12:{14,19,25,58}, :19:{21,30,57}, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:252:62, :253:{17,38}]
  wire              clip_hi_0_3 = $signed(_smul_T_143) > 65'sh7FFFFFFF;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_hi_1_3 = $signed(_smul_T_148) > 65'sh7FFFFFFF;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31]
  wire              clip_lo_0_3 = $signed(_smul_T_143) < -65'sh80000000;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire              clip_lo_1_3 = $signed(_smul_T_148) < -65'sh80000000;	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :258:31]
  wire [31:0]       _clipped_sew_3_long_T_2 = (clip_hi_0_3 ? 32'h7FFFFFFF : 32'h0) | {clip_lo_0_3, 31'h0};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:12:58, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:257:31, :258:31, :261:{21,49,54}]
  wire [31:0]       _clipped_sew_3_long_T_11 = (clip_hi_1_3 ? 32'h7FFFFFFF : 32'h0) | {clip_lo_1_3, 31'h0};	// @[generators/saturn/src/main/scala/exu/Rounding.scala:12:58, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:257:31, :258:31, :261:{21,49,54}]
  wire [3:0][127:0] _GEN_1 =
    {{{{{32{_clipped_sew_3_long_T_11[31]}}, _clipped_sew_3_long_T_11} | (clip_hi_1_3 | clip_lo_1_3 ? 64'h0 : _smul_T_148[63:0]), {{32{_clipped_sew_3_long_T_2[31]}}, _clipped_sew_3_long_T_2} | (clip_hi_0_3 | clip_lo_0_3 ? 64'h0 : _smul_T_143[63:0])}},
     {{(clip_hi_3_2 ? 32'h7FFFFFFF : 32'h0) | {clip_lo_3_2, 31'h0} | (clip_hi_3_2 | clip_lo_3_2 ? 32'h0 : _smul_T_138[31:0]), (clip_hi_2_2 ? 32'h7FFFFFFF : 32'h0) | {clip_lo_2_2, 31'h0} | (clip_hi_2_2 | clip_lo_2_2 ? 32'h0 : _smul_T_133[31:0]), (clip_hi_1_2 ? 32'h7FFFFFFF : 32'h0) | {clip_lo_1_2, 31'h0} | (clip_hi_1_2 | clip_lo_1_2 ? 32'h0 : _smul_T_128[31:0]), (clip_hi_0_2 ? 32'h7FFFFFFF : 32'h0) | {clip_lo_0_2, 31'h0} | (clip_hi_0_2 | clip_lo_0_2 ? 32'h0 : _smul_T_123[31:0])}},
     {{(clip_hi_7_1 ? 16'h7FFF : 16'h0) | {clip_lo_7_1, 15'h0} | (clip_hi_7_1 | clip_lo_7_1 ? 16'h0 : _smul_T_118[15:0]), (clip_hi_6_1 ? 16'h7FFF : 16'h0) | {clip_lo_6_1, 15'h0} | (clip_hi_6_1 | clip_lo_6_1 ? 16'h0 : _smul_T_113[15:0]), (clip_hi_5_1 ? 16'h7FFF : 16'h0) | {clip_lo_5_1, 15'h0} | (clip_hi_5_1 | clip_lo_5_1 ? 16'h0 : _smul_T_108[15:0]), (clip_hi_4_1 ? 16'h7FFF : 16'h0) | {clip_lo_4_1, 15'h0} | (clip_hi_4_1 | clip_lo_4_1 ? 16'h0 : _smul_T_103[15:0]), (clip_hi_3_1 ? 16'h7FFF : 16'h0) | {clip_lo_3_1, 15'h0} | (clip_hi_3_1 | clip_lo_3_1 ? 16'h0 : _smul_T_98[15:0]), (clip_hi_2_1 ? 16'h7FFF : 16'h0) | {clip_lo_2_1, 15'h0} | (clip_hi_2_1 | clip_lo_2_1 ? 16'h0 : _smul_T_93[15:0]), (clip_hi_1_1 ? 16'h7FFF : 16'h0) | {clip_lo_1_1, 15'h0} | (clip_hi_1_1 | clip_lo_1_1 ? 16'h0 : _smul_T_88[15:0]), (clip_hi_0_1 ? 16'h7FFF : 16'h0) | {clip_lo_0_1, 15'h0} | (clip_hi_0_1 | clip_lo_0_1 ? 16'h0 : _smul_T_83[15:0])}},
     {{(clip_hi_15 ? 8'h7F : 8'h0) | {clip_lo_15, 7'h0} | (clip_hi_15 | clip_lo_15 ? 8'h0 : _smul_T_78[7:0]), (clip_hi_14 ? 8'h7F : 8'h0) | {clip_lo_14, 7'h0} | (clip_hi_14 | clip_lo_14 ? 8'h0 : _smul_T_73[7:0]), (clip_hi_13 ? 8'h7F : 8'h0) | {clip_lo_13, 7'h0} | (clip_hi_13 | clip_lo_13 ? 8'h0 : _smul_T_68[7:0]), (clip_hi_12 ? 8'h7F : 8'h0) | {clip_lo_12, 7'h0} | (clip_hi_12 | clip_lo_12 ? 8'h0 : _smul_T_63[7:0]), (clip_hi_11 ? 8'h7F : 8'h0) | {clip_lo_11, 7'h0} | (clip_hi_11 | clip_lo_11 ? 8'h0 : _smul_T_58[7:0]), (clip_hi_10 ? 8'h7F : 8'h0) | {clip_lo_10, 7'h0} | (clip_hi_10 | clip_lo_10 ? 8'h0 : _smul_T_53[7:0]), (clip_hi_9 ? 8'h7F : 8'h0) | {clip_lo_9, 7'h0} | (clip_hi_9 | clip_lo_9 ? 8'h0 : _smul_T_48[7:0]), (clip_hi_8 ? 8'h7F : 8'h0) | {clip_lo_8, 7'h0} | (clip_hi_8 | clip_lo_8 ? 8'h0 : _smul_T_43[7:0]), (clip_hi_7 ? 8'h7F : 8'h0) | {clip_lo_7, 7'h0} | (clip_hi_7 | clip_lo_7 ? 8'h0 : _smul_T_38[7:0]), (clip_hi_6 ? 8'h7F : 8'h0) | {clip_lo_6, 7'h0} | (clip_hi_6 | clip_lo_6 ? 8'h0 : _smul_T_33[7:0]), (clip_hi_5 ? 8'h7F : 8'h0) | {clip_lo_5, 7'h0} | (clip_hi_5 | clip_lo_5 ? 8'h0 : _smul_T_28[7:0]), (clip_hi_4 ? 8'h7F : 8'h0) | {clip_lo_4, 7'h0} | (clip_hi_4 | clip_lo_4 ? 8'h0 : _smul_T_23[7:0]), (clip_hi_3 ? 8'h7F : 8'h0) | {clip_lo_3, 7'h0} | (clip_hi_3 | clip_lo_3 ? 8'h0 : _smul_T_18[7:0]), (clip_hi_2 ? 8'h7F : 8'h0) | {clip_lo_2, 7'h0} | (clip_hi_2 | clip_lo_2 ? 8'h0 : _smul_T_13[7:0]), (clip_hi_1 ? 8'h7F : 8'h0) | {clip_lo_1, 7'h0} | (clip_hi_1 | clip_lo_1 ? 8'h0 : _smul_T_8[7:0]), (clip_hi_0 ? 8'h7F : 8'h0) | {clip_lo_0, 7'h0} | (clip_hi_0 | clip_lo_0 ? 8'h0 : _smul_T_3[7:0])}}};	// @[generators/rocket-chip/src/main/scala/util/package.scala:45:27, generators/saturn/src/main/scala/exu/Rounding.scala:12:58, generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:253:38, :257:31, :258:31, :261:{21,49,54,82,87}, :270:14]
  wire [3:0][15:0]  _GEN_2 = {{{{8{clip_hi_1_3 | clip_lo_1_3}}, {8{clip_hi_0_3 | clip_lo_0_3}}}}, {{{4{clip_hi_3_2 | clip_lo_3_2}}, {4{clip_hi_2_2 | clip_lo_2_2}}, {4{clip_hi_1_2 | clip_lo_1_2}}, {4{clip_hi_0_2 | clip_lo_0_2}}}}, {{{2{clip_hi_7_1 | clip_lo_7_1}}, {2{clip_hi_6_1 | clip_lo_6_1}}, {2{clip_hi_5_1 | clip_lo_5_1}}, {2{clip_hi_4_1 | clip_lo_4_1}}, {2{clip_hi_3_1 | clip_lo_3_1}}, {2{clip_hi_2_1 | clip_lo_2_1}}, {2{clip_hi_1_1 | clip_lo_1_1}}, {2{clip_hi_0_1 | clip_lo_0_1}}}}, {{clip_hi_15 | clip_lo_15, clip_hi_14 | clip_lo_14, clip_hi_13 | clip_lo_13, clip_hi_12 | clip_lo_12, clip_hi_11 | clip_lo_11, clip_hi_10 | clip_lo_10, clip_hi_9 | clip_lo_9, clip_hi_8 | clip_lo_8, clip_hi_7 | clip_lo_7, clip_hi_6 | clip_lo_6, clip_hi_5 | clip_lo_5, clip_hi_4 | clip_lo_4, clip_hi_3 | clip_lo_3, clip_hi_2 | clip_lo_2, clip_hi_1 | clip_lo_1, clip_hi_0 | clip_lo_0}}};	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:257:31, :258:31, :265:18, :267:36, :271:10]
  assign io_clipped = _GEN_1[io_eew];	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:238:7, :270:14]
  assign io_sat = _GEN_2[io_eew];	// @[generators/saturn/src/main/scala/exu/int/SegmentedMultiplyPipe.scala:238:7, :271:10]
endmodule

