// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module ShuttleFrontend(	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
  input         clock,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
  input         reset,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
  input         auto_icache_master_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_icache_master_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_icache_master_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_icache_master_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_icache_master_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_icache_master_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_icache_master_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         io_cpu_redirect_flush,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_cpu_redirect_val,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input  [39:0] io_cpu_redirect_pc,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input  [2:0]  io_cpu_redirect_ras_head,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_cpu_sfence_valid,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_cpu_sfence_bits_rs1,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_cpu_sfence_bits_rs2,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input  [38:0] io_cpu_sfence_bits_addr,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_cpu_flush_icache,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_cpu_resp_0_ready,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output        io_cpu_resp_0_valid,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [31:0] io_cpu_resp_0_bits_inst,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [31:0] io_cpu_resp_0_bits_raw_inst,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [39:0] io_cpu_resp_0_bits_pc,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output        io_cpu_resp_0_bits_edge_inst,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output        io_cpu_resp_0_bits_rvc,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output        io_cpu_resp_0_bits_btb_resp_valid,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [5:0]  io_cpu_resp_0_bits_btb_resp_bits_entry,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [7:0]  io_cpu_resp_0_bits_btb_resp_bits_bht_history,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output        io_cpu_resp_0_bits_sfb_br,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output        io_cpu_resp_0_bits_next_pc_valid,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [39:0] io_cpu_resp_0_bits_next_pc_bits,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [2:0]  io_cpu_resp_0_bits_ras_head,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output        io_cpu_resp_0_bits_xcpt,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [63:0] io_cpu_resp_0_bits_xcpt_cause,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [1:0]  io_cpu_resp_0_bits_mem_size,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_cpu_resp_1_ready,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output        io_cpu_resp_1_valid,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [31:0] io_cpu_resp_1_bits_inst,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [31:0] io_cpu_resp_1_bits_raw_inst,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [39:0] io_cpu_resp_1_bits_pc,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output        io_cpu_resp_1_bits_edge_inst,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output        io_cpu_resp_1_bits_rvc,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output        io_cpu_resp_1_bits_btb_resp_valid,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [5:0]  io_cpu_resp_1_bits_btb_resp_bits_entry,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [7:0]  io_cpu_resp_1_bits_btb_resp_bits_bht_history,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output        io_cpu_resp_1_bits_sfb_br,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output        io_cpu_resp_1_bits_next_pc_valid,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [39:0] io_cpu_resp_1_bits_next_pc_bits,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [2:0]  io_cpu_resp_1_bits_ras_head,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output        io_cpu_resp_1_bits_xcpt,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [63:0] io_cpu_resp_1_bits_xcpt_cause,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [1:0]  io_cpu_resp_1_bits_mem_size,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_cpu_btb_update_valid,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input  [5:0]  io_cpu_btb_update_bits_prediction_entry,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input  [38:0] io_cpu_btb_update_bits_pc,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input  [38:0] io_cpu_btb_update_bits_target,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_cpu_btb_update_bits_isValid,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input  [38:0] io_cpu_btb_update_bits_br_pc,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input  [1:0]  io_cpu_btb_update_bits_cfiType,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_cpu_btb_update_bits_mispredict,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_cpu_bht_update_valid,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input  [7:0]  io_cpu_bht_update_bits_prediction_history,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input  [38:0] io_cpu_bht_update_bits_pc,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_cpu_bht_update_bits_branch,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_cpu_bht_update_bits_taken,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_cpu_bht_update_bits_mispredict,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_cpu_ras_update_valid,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input  [2:0]  io_cpu_ras_update_bits_head,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input  [39:0] io_cpu_ras_update_bits_addr,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_req_ready,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output        io_ptw_req_valid,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output [26:0] io_ptw_req_bits_bits_addr,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  output        io_ptw_req_bits_bits_need_gpa,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_valid,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_bits_ae_ptw,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_bits_ae_final,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_bits_pf,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_bits_gf,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_bits_hr,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_bits_hw,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_bits_hx,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input  [43:0] io_ptw_resp_bits_pte_ppn,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_bits_pte_d,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_bits_pte_a,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_bits_pte_g,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_bits_pte_u,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_bits_pte_x,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_bits_pte_w,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_bits_pte_r,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_bits_pte_v,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input  [1:0]  io_ptw_resp_bits_level,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_resp_bits_homogeneous,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input  [3:0]  io_ptw_ptbr_mode,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input         io_ptw_status_debug,	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
  input  [1:0]  io_ptw_status_prv	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
);

  wire             f1_clear;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:325:58, :330:14, :331:38, :356:32, :360:17, :370:24, :377:17]
  wire             f2_clear;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:356:32, :370:24, :374:17]
  wire             valid_3;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:310:16]
  wire             _valid_T_18;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:310:76]
  wire [31:0]      f2_fetch_bundle_exp_insts_3;	// @[generators/shuttle/src/main/scala/common/Consts.scala:43:8]
  wire             f2_fetch_bundle_next_pc_valid;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:280:18, :281:22]
  wire             f2_ret_mask_3;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:260:65]
  wire             f2_inst_mask_3;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:267:62]
  wire             valid_2;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:316:16]
  wire             _valid_T_9;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:316:36]
  wire [31:0]      f2_fetch_bundle_exp_insts_2;	// @[generators/shuttle/src/main/scala/common/Consts.scala:43:8]
  wire             f2_ret_mask_2;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:260:65]
  wire             f2_inst_mask_2;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:267:62]
  wire             valid_1;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:304:32]
  wire [31:0]      f2_fetch_bundle_exp_insts_1;	// @[generators/shuttle/src/main/scala/common/Consts.scala:43:8]
  wire             f2_ret_mask_1;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:260:65]
  wire             f2_inst_mask_1;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:267:62]
  wire [31:0]      f2_fetch_bundle_exp_insts_0;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:287:30, :290:38, :295:38]
  wire [31:0]      f2_fetch_bundle_insts_0;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:287:30, :289:38, :294:38]
  wire             f2_ret_mask_0;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:260:65]
  wire             f2_inst_mask_0;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:267:33]
  wire             _fb_io_enq_ready;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:346:18]
  wire [31:0]      _expanded_rvc_exp_4_io_out_bits;	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25]
  wire             _expanded_rvc_exp_4_io_rvc;	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25]
  wire [31:0]      _expanded_rvc_exp_3_io_out_bits;	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25]
  wire             _expanded_rvc_exp_3_io_rvc;	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25]
  wire [31:0]      _expanded_rvc_exp_2_io_out_bits;	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25]
  wire             _expanded_rvc_exp_2_io_rvc;	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25]
  wire [31:0]      _expanded_rvc_exp_1_io_out_bits;	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25]
  wire             _expanded_rvc_exp_1_io_rvc;	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25]
  wire [31:0]      _expanded_rvc_exp_io_out_bits;	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25]
  wire             _expanded_rvc_exp_io_rvc;	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25]
  wire             _btb_io_resp_valid;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:109:19]
  wire             _btb_io_resp_bits_taken;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:109:19]
  wire [1:0]       _btb_io_resp_bits_bridx;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:109:19]
  wire [38:0]      _btb_io_resp_bits_target;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:109:19]
  wire [5:0]       _btb_io_resp_bits_entry;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:109:19]
  wire [7:0]       _btb_io_resp_bits_bht_history;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:109:19]
  wire             _btb_io_resp_bits_bht_value;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:109:19]
  wire             _tlb_io_resp_miss;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:107:19]
  wire [31:0]      _tlb_io_resp_paddr;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:107:19]
  wire             _tlb_io_resp_pf_inst;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:107:19]
  wire             _tlb_io_resp_ae_inst;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:107:19]
  wire             _icache_io_resp_valid;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26]
  wire [63:0]      _icache_io_resp_bits;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26]
  reg  [39:0]      ras_0;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16]
  reg  [39:0]      ras_1;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16]
  reg  [39:0]      ras_2;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16]
  reg  [39:0]      ras_3;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16]
  reg  [39:0]      ras_4;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16]
  reg  [39:0]      ras_5;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16]
  reg  [39:0]      s1_vpc;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:137:29]
  reg  [2:0]       s1_ras_head_REG;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:138:38]
  reg              s1_valid;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:139:29]
  reg              s1_is_replay;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:140:29]
  reg              s1_tlb_resp_REG_pf_inst;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:159:46]
  reg              s1_tlb_resp_REG_ae_inst;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:159:46]
  reg  [31:0]      s1_ppc_REG;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:160:42]
  wire [31:0]      s1_ppc = s1_is_replay ? s1_ppc_REG : _tlb_io_resp_paddr;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:107:19, :140:29, :160:{20,42}]
  wire [39:0]      _f1_next_fetch_T_3 = {s1_vpc[39:3], 3'h0} + 40'h8;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:22:48, :125:29, :137:29]
  wire             f1_do_redirect = _btb_io_resp_valid & _btb_io_resp_bits_taken;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:109:19, :168:42]
  wire [39:0]      _f1_predicted_target_T_1 = {_btb_io_resp_bits_target[38], _btb_io_resp_bits_target};	// @[generators/rocket-chip/src/main/scala/util/package.scala:132:{15,38}, generators/shuttle/src/main/scala/ifu/Frontend.scala:109:19]
  wire [39:0]      f1_predicted_target = f1_do_redirect ? _f1_predicted_target_T_1 : _f1_next_fetch_T_3;	// @[generators/rocket-chip/src/main/scala/util/package.scala:132:15, generators/shuttle/src/main/scala/ifu/Frontend.scala:22:48, :168:42, :169:32]
  reg              s2_valid;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:185:25]
  reg  [39:0]      s2_vpc;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:186:25]
  reg  [31:0]      s2_ppc;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:187:24]
  reg  [2:0]       s2_ras_head;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:188:28]
  reg              s2_tlb_resp_pf_inst;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:190:28]
  reg              s2_tlb_resp_ae_inst;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:190:28]
  reg              s2_tlb_miss;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:191:28]
  reg              s2_is_replay_REG;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:192:29]
  wire             s2_is_replay = s2_is_replay_REG & s2_valid;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:185:25, :192:{29,44}]
  wire             _fb_io_enq_valid_T_2 = s2_tlb_resp_ae_inst | s2_tlb_resp_pf_inst;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:190:28, :193:50]
  reg              s2_btb_resp_valid;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:194:28]
  reg              s2_btb_resp_bits_taken;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:194:28]
  reg  [1:0]       s2_btb_resp_bits_bridx;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:194:28]
  reg  [5:0]       s2_btb_resp_bits_entry;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:194:28]
  reg  [7:0]       s2_btb_resp_bits_bht_history;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:194:28]
  reg              s2_btb_resp_bits_bht_value;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:194:28]
  wire [6:0]       f2_fetch_mask = 7'hF << s2_vpc[2:1];	// @[generators/rocket-chip/src/main/scala/util/package.scala:163:13, generators/shuttle/src/main/scala/ifu/Frontend.scala:25:37, :186:25]
  wire [3:0]       _f2_do_ret_T_2 = {f2_ret_mask_3, f2_ret_mask_2, f2_ret_mask_1, f2_ret_mask_0} & {f2_inst_mask_3, f2_inst_mask_2, f2_inst_mask_1, f2_inst_mask_0};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:208:{33,40,55}, :260:65, :267:{33,62}]
  reg  [39:0]      f2_predicted_target_REG;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:214:45]
  wire [7:0][39:0] _GEN = {{ras_0}, {ras_0}, {ras_5}, {ras_4}, {ras_3}, {ras_2}, {ras_1}, {ras_0}};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16, :214:8]
  reg  [39:0]      f2_predicted_target_REG_1;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:215:12]
  wire [39:0]      f2_fetch_bundle_next_pc_bits = f2_fetch_bundle_next_pc_valid ? ((|_f2_do_ret_T_2) ? _GEN[s2_ras_head] : f2_predicted_target_REG) : f2_predicted_target_REG_1;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:188:28, :208:{40,63}, :213:32, :214:{8,45}, :215:12, :280:18, :281:22]
  wire [39:0]      _GEN_0 = {s2_vpc[39:3], 3'h0};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:125:29, :186:25, :229:39]
  reg              REG;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:233:44]
  reg  [2:0]       idx_REG;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:234:80]
  reg  [39:0]      addr_REG;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:235:81]
  reg  [15:0]      f2_prev_half;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:240:25]
  reg              f2_prev_is_half;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:242:32]
  assign f2_inst_mask_0 = s2_valid & f2_fetch_mask[0];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:25:37, :185:25, :267:{33,49}]
  assign f2_ret_mask_0 = f2_fetch_bundle_exp_insts_0[6:0] == 7'h67 & ~(f2_fetch_bundle_exp_insts_0[7]) & {f2_fetch_bundle_exp_insts_0[19:18], f2_fetch_bundle_exp_insts_0[16:15]} == 4'h1;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:257:{40,46}, :259:82, :260:{52,65,85}, :287:30, :290:38, :295:38]
  wire             redir = f2_inst_mask_0 & (f2_fetch_bundle_exp_insts_0[6:0] == 7'h67 | f2_fetch_bundle_exp_insts_0[6:0] == 7'h6F | f2_fetch_bundle_exp_insts_0[6:0] == 7'h63 & s2_btb_resp_valid & s2_btb_resp_bits_bridx == 2'h0 & s2_btb_resp_bits_taken & s2_btb_resp_bits_bht_value);	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:116:27, :194:28, :257:{40,46}, :258:46, :261:45, :267:33, :269:65, :277:56, :279:{33,114}, :287:30, :290:38, :295:38]
  wire [31:0]      _expanded_T_1 = {_icache_io_resp_bits[15:0], f2_prev_half};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :240:25, :288:{37,49}]
  assign f2_fetch_bundle_insts_0 = f2_prev_is_half ? {_icache_io_resp_bits[15:0], f2_prev_half} : _icache_io_resp_bits[31:0];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :240:25, :242:32, :287:30, :288:49, :289:{38,44}, :293:45, :294:38]
  assign f2_fetch_bundle_exp_insts_0 = f2_prev_is_half ? (_expanded_rvc_exp_io_rvc ? _expanded_rvc_exp_io_out_bits : _expanded_T_1) : _expanded_rvc_exp_1_io_rvc ? _expanded_rvc_exp_1_io_out_bits : _icache_io_resp_bits[31:0];	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25, :43:8, generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :242:32, :287:30, :288:37, :290:38, :293:45, :295:38]
  assign f2_inst_mask_1 = s2_valid & f2_fetch_mask[1] & valid_1 & ~redir;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:25:37, :185:25, :267:{49,62,65}, :279:33, :304:32]
  wire             _redir_br_T_9 = s2_btb_resp_bits_bridx == 2'h1;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:194:28, :269:65, :282:25]
  assign f2_ret_mask_1 = f2_fetch_bundle_exp_insts_1[6:0] == 7'h67 & ~(f2_fetch_bundle_exp_insts_1[7]) & {f2_fetch_bundle_exp_insts_1[19:18], f2_fetch_bundle_exp_insts_1[16:15]} == 4'h1;	// @[generators/shuttle/src/main/scala/common/Consts.scala:43:8, generators/shuttle/src/main/scala/ifu/Frontend.scala:257:{40,46}, :259:82, :260:{52,65,85}]
  wire             redir_1 = f2_inst_mask_1 & (f2_fetch_bundle_exp_insts_1[6:0] == 7'h67 | f2_fetch_bundle_exp_insts_1[6:0] == 7'h6F | f2_fetch_bundle_exp_insts_1[6:0] == 7'h63 & s2_btb_resp_valid & _redir_br_T_9 & s2_btb_resp_bits_taken & s2_btb_resp_bits_bht_value);	// @[generators/shuttle/src/main/scala/common/Consts.scala:43:8, generators/shuttle/src/main/scala/ifu/Frontend.scala:194:28, :257:{40,46}, :258:46, :261:45, :267:62, :269:65, :277:56, :279:{33,114}]
  wire             _GEN_1 = redir | redir_1;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:279:33, :284:31]
  assign f2_fetch_bundle_exp_insts_1 = _expanded_rvc_exp_2_io_rvc ? _expanded_rvc_exp_2_io_out_bits : _icache_io_resp_bits[47:16];	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25, :43:8, generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :300:29]
  assign valid_1 = f2_prev_is_half | ~(f2_inst_mask_0 & (&(f2_fetch_bundle_insts_0[1:0])));	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:242:32, :255:{32,38}, :267:33, :287:30, :289:38, :294:38, :304:{32,35,55}]
  assign f2_inst_mask_2 = s2_valid & f2_fetch_mask[2] & valid_2 & ~_GEN_1;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:25:37, :185:25, :267:{49,62,65}, :284:31, :316:16]
  wire             _redir_br_T_16 = s2_btb_resp_bits_bridx == 2'h2;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:194:28, :229:71, :269:65]
  assign f2_ret_mask_2 = f2_fetch_bundle_exp_insts_2[6:0] == 7'h67 & ~(f2_fetch_bundle_exp_insts_2[7]) & {f2_fetch_bundle_exp_insts_2[19:18], f2_fetch_bundle_exp_insts_2[16:15]} == 4'h1;	// @[generators/shuttle/src/main/scala/common/Consts.scala:43:8, generators/shuttle/src/main/scala/ifu/Frontend.scala:257:{40,46}, :259:82, :260:{52,65,85}]
  wire             redir_2 = f2_inst_mask_2 & (f2_fetch_bundle_exp_insts_2[6:0] == 7'h67 | f2_fetch_bundle_exp_insts_2[6:0] == 7'h6F | f2_fetch_bundle_exp_insts_2[6:0] == 7'h63 & s2_btb_resp_valid & _redir_br_T_16 & s2_btb_resp_bits_taken & s2_btb_resp_bits_bht_value);	// @[generators/shuttle/src/main/scala/common/Consts.scala:43:8, generators/shuttle/src/main/scala/ifu/Frontend.scala:194:28, :257:{40,46}, :258:46, :261:45, :267:62, :269:65, :277:56, :279:{33,114}]
  assign f2_fetch_bundle_exp_insts_2 = _expanded_rvc_exp_3_io_rvc ? _expanded_rvc_exp_3_io_out_bits : _icache_io_resp_bits[63:32];	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25, :43:8, generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :312:29]
  assign _valid_T_9 = f2_inst_mask_1 & (&(_icache_io_resp_bits[17:16]));	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :255:{32,38}, :267:62, :316:36]
  assign valid_2 = ~_valid_T_9;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:316:{16,36}]
  assign f2_inst_mask_3 = s2_valid & f2_fetch_mask[3] & valid_3 & ~(_GEN_1 | redir_2);	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:25:37, :185:25, :267:{49,62,65}, :279:33, :284:31, :310:16]
  assign f2_ret_mask_3 = f2_fetch_bundle_exp_insts_3[6:0] == 7'h67 & ~(f2_fetch_bundle_exp_insts_3[7]) & {f2_fetch_bundle_exp_insts_3[19:18], f2_fetch_bundle_exp_insts_3[16:15]} == 4'h1;	// @[generators/shuttle/src/main/scala/common/Consts.scala:43:8, generators/shuttle/src/main/scala/ifu/Frontend.scala:257:{40,46}, :259:82, :260:{52,65,85}]
  wire             redir_3 = f2_inst_mask_3 & (f2_fetch_bundle_exp_insts_3[6:0] == 7'h67 | f2_fetch_bundle_exp_insts_3[6:0] == 7'h6F | f2_fetch_bundle_exp_insts_3[6:0] == 7'h63 & s2_btb_resp_valid & (&s2_btb_resp_bits_bridx) & s2_btb_resp_bits_taken & s2_btb_resp_bits_bht_value);	// @[generators/shuttle/src/main/scala/common/Consts.scala:43:8, generators/shuttle/src/main/scala/ifu/Frontend.scala:194:28, :257:{40,46}, :258:46, :261:45, :267:62, :269:65, :277:56, :279:{33,114}]
  assign f2_fetch_bundle_next_pc_valid = redir_3 | redir_2 | redir_1 | redir;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:279:33, :280:18, :281:22]
  wire [31:0]      f2_fetch_bundle_insts_3 = {16'h0, _icache_io_resp_bits[63:48]};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :306:{21,44}]
  assign f2_fetch_bundle_exp_insts_3 = _expanded_rvc_exp_4_io_rvc ? _expanded_rvc_exp_4_io_out_bits : f2_fetch_bundle_insts_3;	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25, :43:8, generators/shuttle/src/main/scala/ifu/Frontend.scala:306:21]
  assign _valid_T_18 = f2_inst_mask_2 & (&(_icache_io_resp_bits[33:32])) | (&(_icache_io_resp_bits[49:48]));	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :255:{32,38}, :267:62, :310:{37,76}]
  assign valid_3 = ~_valid_T_18;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:310:{16,76}]
  wire             _s0_is_replay_T = s2_valid & _icache_io_resp_valid;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :185:25, :325:19]
  wire             _GEN_2 = s2_valid & ~_icache_io_resp_valid | _s0_is_replay_T & ~_fb_io_enq_ready;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :185:25, :324:{19,22,45}, :325:{19,43,46}, :346:18]
  wire             _GEN_3 = s2_valid & _fb_io_enq_ready;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:185:25, :331:25, :346:18]
  wire             _GEN_4 = s1_valid & s1_vpc != f2_fetch_bundle_next_pc_bits | ~s1_valid;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:137:29, :139:29, :213:32, :334:{21,32,58,61}]
  wire             _GEN_5 = _GEN_3 & _GEN_4;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:141:30, :331:{25,38}, :334:{58,72}]
  wire             _GEN_6 = _GEN_3 & _GEN_4;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:173:19, :331:{25,38}, :334:{58,72}, :337:20]
  reg              jump_to_reset;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:368:30]
  wire             s0_valid = jump_to_reset | (io_cpu_redirect_flush ? io_cpu_redirect_val : _GEN_2 ? ~s2_tlb_resp_ae_inst & ~s2_tlb_resp_pf_inst | s2_is_replay | s2_tlb_miss | ~_fb_io_enq_ready : _GEN_6 ? ~(_fb_io_enq_valid_T_2 & ~s2_is_replay) : s1_valid);	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:139:29, :173:19, :190:28, :191:28, :192:44, :193:{50,77}, :324:45, :325:{46,58}, :326:{14,18,39,42,95}, :331:38, :334:72, :337:{20,23,70}, :346:18, :356:32, :362:18, :368:30, :370:24, :371:14]
  assign f2_clear = jump_to_reset | io_cpu_redirect_flush;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:356:32, :368:30, :370:24, :374:17]
  assign f1_clear = jump_to_reset | io_cpu_redirect_flush | _GEN_2 | _GEN_5;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:141:30, :324:45, :325:58, :330:14, :331:38, :334:72, :356:32, :360:17, :368:30, :370:24, :377:17]
  wire [3:0]       _f2_do_call_T_2 = {(f2_fetch_bundle_exp_insts_3[6:0] == 7'h67 | f2_fetch_bundle_exp_insts_3[6:0] == 7'h6F) & f2_fetch_bundle_exp_insts_3[7], (f2_fetch_bundle_exp_insts_2[6:0] == 7'h67 | f2_fetch_bundle_exp_insts_2[6:0] == 7'h6F) & f2_fetch_bundle_exp_insts_2[7], (f2_fetch_bundle_exp_insts_1[6:0] == 7'h67 | f2_fetch_bundle_exp_insts_1[6:0] == 7'h6F) & f2_fetch_bundle_exp_insts_1[7], (f2_fetch_bundle_exp_insts_0[6:0] == 7'h67 | f2_fetch_bundle_exp_insts_0[6:0] == 7'h6F) & f2_fetch_bundle_exp_insts_0[7]} & {f2_inst_mask_3, f2_inst_mask_2, f2_inst_mask_1, f2_inst_mask_0};	// @[generators/shuttle/src/main/scala/common/Consts.scala:43:8, generators/shuttle/src/main/scala/ifu/Frontend.scala:207:{34,41,56}, :257:{40,46}, :258:46, :259:{50,71,82}, :267:{33,62}, :287:30, :290:38, :295:38]
  wire             _ras_next_head_T = s2_ras_head == 3'h5;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:188:28, :221:55]
  wire [2:0]       _ras_next_head_T_1 = s2_ras_head + 3'h1;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:188:28, :221:98, :236:14]
  wire             _ras_next_head_T_4 = s2_ras_head == 3'h0;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:125:29, :188:28, :222:36]
  wire [2:0]       _ras_next_head_T_5 = s2_ras_head - 3'h1;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:188:28, :222:79]
  wire             _GEN_7 = ((|_f2_do_call_T_2) | (|_f2_do_ret_T_2)) & s2_valid & _fb_io_enq_ready & _icache_io_resp_valid;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :185:25, :207:{41,64}, :208:{40,63}, :223:{21,59}, :346:18]
  wire             _GEN_8 = _GEN_7 & (|_f2_do_call_T_2);	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:207:{41,64}, :219:31, :223:{59,84}, :226:23, :228:21]
  wire             _GEN_9 = io_cpu_ras_update_valid | REG & ~io_cpu_redirect_val;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:233:{33,44,62,84}]
  wire [2:0]       idx = io_cpu_ras_update_valid ? io_cpu_ras_update_bits_head : idx_REG;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:234:{18,80}]
  wire [39:0]      addr = io_cpu_ras_update_valid ? io_cpu_ras_update_bits_addr : addr_REG;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:235:{19,81}]
  wire             _GEN_10 = _GEN_2 | ~_GEN_3;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:242:32, :324:45, :325:58, :331:{25,38}]
  wire [2:0]       ras_next_head = (|_f2_do_call_T_2) ? (_ras_next_head_T ? 3'h0 : _ras_next_head_T_1) : (|_f2_do_ret_T_2) ? (_ras_next_head_T_4 ? 3'h5 : _ras_next_head_T_5) : s2_ras_head;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:125:29, :188:28, :207:{41,64}, :208:{40,63}, :221:{26,42,55,98}, :222:{8,23,36,79}]
  wire [3:0]       _GEN_11 = {{&(_icache_io_resp_bits[49:48])}, {&(_icache_io_resp_bits[33:32])}, {&(_icache_io_resp_bits[17:16])}, {(&(f2_fetch_bundle_insts_0[1:0])) & ~f2_prev_is_half}};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :229:71, :242:32, :255:{32,38}, :276:{64,67}, :287:30, :289:38, :294:38]
  always @(posedge clock) begin	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
    if (_GEN_9 & idx == 3'h0)	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16, :125:29, :233:{33,111}, :234:18, :236:14]
      ras_0 <= addr;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16, :235:19]
    if (_GEN_9 & idx == 3'h1)	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16, :233:{33,111}, :234:18, :236:14]
      ras_1 <= addr;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16, :235:19]
    if (_GEN_9 & idx == 3'h2)	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16, :233:{33,111}, :234:18, :236:14]
      ras_2 <= addr;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16, :235:19]
    if (_GEN_9 & idx == 3'h3)	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16, :233:{33,111}, :234:18, :236:14]
      ras_3 <= addr;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16, :235:19]
    if (_GEN_9 & idx == 3'h4)	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16, :229:71, :233:{33,111}, :234:18, :236:14]
      ras_4 <= addr;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16, :235:19]
    if (_GEN_9 & idx == 3'h5)	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16, :221:55, :233:{33,111}, :234:18, :236:14]
      ras_5 <= addr;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:110:16, :235:19]
    if (jump_to_reset) begin	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:368:30]
      s1_vpc <= 40'h10000;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:137:29, :372:14]
      s1_ras_head_REG <= 3'h5;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:138:38, :221:55]
    end
    else if (io_cpu_redirect_flush) begin	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14]
      s1_vpc <= io_cpu_redirect_pc;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:137:29]
      s1_ras_head_REG <= io_cpu_redirect_ras_head;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:138:38]
    end
    else if (_GEN_2) begin	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:324:45]
      s1_vpc <= s2_vpc;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:137:29, :186:25]
      s1_ras_head_REG <= s2_ras_head;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:138:38, :188:28]
    end
    else begin	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:324:45]
      if (_GEN_6)	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:173:19, :331:38, :334:72, :337:20]
        s1_vpc <= f2_fetch_bundle_next_pc_bits;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:137:29, :213:32]
      else if (s1_valid) begin	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:139:29]
        if (f1_do_redirect)	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:168:42]
          s1_vpc <= _f1_predicted_target_T_1;	// @[generators/rocket-chip/src/main/scala/util/package.scala:132:15, generators/shuttle/src/main/scala/ifu/Frontend.scala:137:29]
        else	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:168:42]
          s1_vpc <= _f1_next_fetch_T_3;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:22:48, :137:29]
      end
      else	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:139:29]
        s1_vpc <= 40'h0;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:123:24, :137:29]
      if (_GEN_5 | _GEN_7)	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:141:30, :173:19, :223:{59,84}, :224:17, :331:38, :334:72, :339:20]
        s1_ras_head_REG <= ras_next_head;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:138:38, :221:26]
      else if (s1_valid) begin	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:139:29]
        if (_GEN_7)	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:223:59]
          s1_ras_head_REG <= ras_next_head;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:138:38, :221:26]
      end
      else	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:139:29]
        s1_ras_head_REG <= 3'h0;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:125:29, :138:38]
    end
    s1_is_replay <= ~io_cpu_redirect_flush & _GEN_2 & _s0_is_replay_T;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:140:29, :324:45, :325:{19,58}, :356:32, :365:18]
    s1_tlb_resp_REG_pf_inst <= s2_tlb_resp_pf_inst;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:159:46, :190:28]
    s1_tlb_resp_REG_ae_inst <= s2_tlb_resp_ae_inst;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:159:46, :190:28]
    s1_ppc_REG <= s2_ppc;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:160:42, :187:24]
    s2_vpc <= s1_vpc;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:137:29, :186:25]
    s2_ppc <= s1_ppc;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:160:20, :187:24]
    if (_GEN_7) begin	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:223:59]
      if (|_f2_do_call_T_2) begin	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:207:{41,64}]
        if (_ras_next_head_T)	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:221:55]
          s2_ras_head <= 3'h0;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:125:29, :188:28]
        else	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:221:55]
          s2_ras_head <= _ras_next_head_T_1;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:188:28, :221:98]
      end
      else if (|_f2_do_ret_T_2) begin	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:208:{40,63}]
        if (_ras_next_head_T_4)	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:222:36]
          s2_ras_head <= 3'h5;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:188:28, :221:55]
        else	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:222:36]
          s2_ras_head <= _ras_next_head_T_5;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:188:28, :222:79]
      end
    end
    else	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:223:59]
      s2_ras_head <= s1_ras_head_REG;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:138:38, :188:28]
    s2_tlb_resp_pf_inst <= s1_is_replay ? s1_tlb_resp_REG_pf_inst : _tlb_io_resp_pf_inst;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:107:19, :140:29, :159:{24,46}, :190:28]
    s2_tlb_resp_ae_inst <= s1_is_replay ? s1_tlb_resp_REG_ae_inst : _tlb_io_resp_ae_inst;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:107:19, :140:29, :159:{24,46}, :190:28]
    s2_tlb_miss <= ~s1_is_replay & (_tlb_io_resp_miss | io_cpu_sfence_valid);	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:107:19, :140:29, :143:41, :158:{35,56}, :191:28]
    s2_is_replay_REG <= s1_is_replay;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:140:29, :192:29]
    s2_btb_resp_valid <= _btb_io_resp_valid;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:109:19, :194:28]
    s2_btb_resp_bits_taken <= _btb_io_resp_bits_taken;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:109:19, :194:28]
    s2_btb_resp_bits_bridx <= _btb_io_resp_bits_bridx;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:109:19, :194:28]
    s2_btb_resp_bits_entry <= _btb_io_resp_bits_entry;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:109:19, :194:28]
    s2_btb_resp_bits_bht_history <= _btb_io_resp_bits_bht_history;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:109:19, :194:28]
    s2_btb_resp_bits_bht_value <= _btb_io_resp_bits_bht_value;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:109:19, :194:28]
    f2_predicted_target_REG <= f1_predicted_target;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:169:32, :214:45]
    f2_predicted_target_REG_1 <= _f1_next_fetch_T_3;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:22:48, :215:12]
    REG <= _GEN_7 & (|_f2_do_call_T_2) & ~io_cpu_redirect_val;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:207:{41,64}, :223:59, :233:{44,59,62}]
    idx_REG <= ~_GEN_8 | _ras_next_head_T ? 3'h0 : _ras_next_head_T_1;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:125:29, :219:31, :221:{55,98}, :223:84, :226:23, :228:21, :234:80]
    addr_REG <= _GEN_8 ? _GEN_0 + {37'h0, redir_3 ? 2'h3 : redir_2 ? 2'h2 : {1'h0, redir_1}, 1'h0} + {37'h0, _GEN_11[s2_btb_resp_bits_bridx] ? 3'h4 : 3'h2} : 40'h0;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:112:16, :123:24, :147:25, :194:28, :219:31, :220:32, :223:84, :226:23, :228:21, :229:{22,39,66,71}, :235:81, :236:14, :279:33, :280:18, :282:25]
    if (_GEN_10) begin	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:240:25, :242:32, :325:58, :331:38]
    end
    else	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:240:25, :325:58, :331:38]
      f2_prev_half <= _icache_io_resp_bits[63:48];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :240:25, :306:44]
    if (reset) begin	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
      s1_valid <= 1'h0;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:112:16, :139:29]
      s2_valid <= 1'h0;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:112:16, :185:25]
      f2_prev_is_half <= 1'h0;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:112:16, :242:32]
      jump_to_reset <= 1'h1;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:175:18, :368:30]
    end
    else begin	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
      s1_valid <= s0_valid;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:139:29, :356:32, :370:24, :371:14]
      s2_valid <= s1_valid & ~f1_clear;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:139:29, :143:58, :185:{25,35}, :325:58, :330:14, :331:38, :356:32, :360:17, :370:24, :377:17]
      f2_prev_is_half <= ~(jump_to_reset | io_cpu_redirect_flush) & (_GEN_10 ? f2_prev_is_half : ~(f2_inst_mask_2 & (&(_icache_io_resp_bits[33:32]))) & (&(_icache_io_resp_bits[49:48])) & ~f2_fetch_bundle_next_pc_valid);	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :242:32, :255:{32,38}, :267:62, :280:18, :281:22, :319:54, :320:{38,67}, :325:58, :331:38, :332:{55,58}, :356:32, :359:21, :368:30, :370:24, :376:21]
      jump_to_reset <= 1'h0;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:112:16, :368:30]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:26];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
    initial begin	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
        `INIT_RANDOM_PROLOG_	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
        for (logic [4:0] i = 5'h0; i < 5'h1B; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
        end	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
        ras_0 = {_RANDOM[5'h0], _RANDOM[5'h1][7:0]};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :110:16]
        ras_1 = {_RANDOM[5'h1][31:8], _RANDOM[5'h2][15:0]};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :110:16]
        ras_2 = {_RANDOM[5'h2][31:16], _RANDOM[5'h3][23:0]};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :110:16]
        ras_3 = {_RANDOM[5'h3][31:24], _RANDOM[5'h4]};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :110:16]
        ras_4 = {_RANDOM[5'h5], _RANDOM[5'h6][7:0]};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :110:16]
        ras_5 = {_RANDOM[5'h6][31:8], _RANDOM[5'h7][15:0]};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :110:16]
        s1_vpc = {_RANDOM[5'h7][31:16], _RANDOM[5'h8][23:0]};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :110:16, :137:29]
        s1_ras_head_REG = _RANDOM[5'h8][26:24];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :137:29, :138:38]
        s1_valid = _RANDOM[5'h8][27];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :137:29, :139:29]
        s1_is_replay = _RANDOM[5'h8][28];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :137:29, :140:29]
        s1_tlb_resp_REG_pf_inst = _RANDOM[5'hB][9];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :159:46]
        s1_tlb_resp_REG_ae_inst = _RANDOM[5'hB][15];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :159:46]
        s1_ppc_REG = {_RANDOM[5'hB][31:29], _RANDOM[5'hC][28:0]};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :159:46, :160:42]
        s2_valid = _RANDOM[5'hC][29];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :160:42, :185:25]
        s2_vpc = {_RANDOM[5'hC][31:30], _RANDOM[5'hD], _RANDOM[5'hE][5:0]};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :160:42, :186:25]
        s2_ppc = {_RANDOM[5'hE][31:6], _RANDOM[5'hF][5:0]};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :186:25, :187:24]
        s2_ras_head = _RANDOM[5'hF][8:6];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :187:24, :188:28]
        s2_tlb_resp_pf_inst = _RANDOM[5'h11][21];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :190:28]
        s2_tlb_resp_ae_inst = _RANDOM[5'h11][27];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :190:28]
        s2_tlb_miss = _RANDOM[5'h12][9];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :191:28]
        s2_is_replay_REG = _RANDOM[5'h12][10];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :191:28, :192:29]
        s2_btb_resp_valid = _RANDOM[5'h12][11];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :191:28, :194:28]
        s2_btb_resp_bits_taken = _RANDOM[5'h12][14];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :191:28, :194:28]
        s2_btb_resp_bits_bridx = _RANDOM[5'h12][20:19];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :191:28, :194:28]
        s2_btb_resp_bits_entry = {_RANDOM[5'h13][31:28], _RANDOM[5'h14][1:0]};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :194:28]
        s2_btb_resp_bits_bht_history = _RANDOM[5'h14][9:2];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :194:28]
        s2_btb_resp_bits_bht_value = _RANDOM[5'h14][10];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :194:28]
        f2_predicted_target_REG = {_RANDOM[5'h15][31:19], _RANDOM[5'h16][26:0]};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :214:45]
        f2_predicted_target_REG_1 = {_RANDOM[5'h16][31:27], _RANDOM[5'h17], _RANDOM[5'h18][2:0]};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :214:45, :215:12]
        REG = _RANDOM[5'h18][3];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :215:12, :233:44]
        idx_REG = _RANDOM[5'h18][6:4];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :215:12, :234:80]
        addr_REG = {_RANDOM[5'h18][31:7], _RANDOM[5'h19][14:0]};	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :215:12, :235:81]
        f2_prev_half = _RANDOM[5'h19][30:15];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :235:81, :240:25]
        f2_prev_is_half = _RANDOM[5'h19][31];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :235:81, :242:32]
        jump_to_reset = _RANDOM[5'h1A][0];	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7, :368:30]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:93:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ShuttleICache icache (	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26]
    .clock                          (clock),
    .reset                          (reset),
    .auto_master_out_a_ready        (auto_icache_master_out_a_ready),
    .auto_master_out_a_valid        (auto_icache_master_out_a_valid),
    .auto_master_out_a_bits_address (auto_icache_master_out_a_bits_address),
    .auto_master_out_d_valid        (auto_icache_master_out_d_valid),
    .auto_master_out_d_bits_opcode  (auto_icache_master_out_d_bits_opcode),
    .auto_master_out_d_bits_size    (auto_icache_master_out_d_bits_size),
    .auto_master_out_d_bits_data    (auto_icache_master_out_d_bits_data),
    .io_req_valid                   (s0_valid),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:356:32, :370:24, :371:14]
    .io_req_bits                    (jump_to_reset ? 39'h10000 : io_cpu_redirect_flush ? io_cpu_redirect_pc[38:0] : _GEN_2 ? s2_vpc[38:0] : _GEN_6 ? f2_fetch_bundle_next_pc_bits[38:0] : s1_valid ? f1_predicted_target[38:0] : 39'h0),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:98:14, :123:24, :139:29, :169:32, :173:19, :176:18, :186:25, :213:32, :324:45, :325:58, :327:14, :331:38, :334:72, :337:20, :338:20, :356:32, :363:18, :368:30, :370:24, :372:14]
    .io_s1_kill                     (_tlb_io_resp_miss | f1_clear),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:107:19, :163:42, :325:58, :330:14, :331:38, :356:32, :360:17, :370:24, :377:17]
    .io_s2_kill                     (s2_valid & _fb_io_enq_valid_T_2 & ~s2_is_replay),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:185:25, :192:44, :193:{50,74,77}]
    .io_s1_paddr                    (s1_ppc),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:160:20]
    .io_invalidate                  (io_cpu_flush_icache),
    .io_resp_valid                  (_icache_io_resp_valid),
    .io_resp_bits                   (_icache_io_resp_bits)
  );
  ITLB tlb (	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:107:19]
    .clock                         (clock),
    .reset                         (reset),
    .io_req_valid                  (s1_valid & ~s1_is_replay & ~f1_clear & ~io_cpu_sfence_valid),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:139:29, :140:29, :143:{41,58,68,71}, :325:58, :330:14, :331:38, :356:32, :360:17, :370:24, :377:17]
    .io_req_bits_vaddr             (io_cpu_sfence_valid ? {1'h0, io_cpu_sfence_bits_addr} : s1_vpc),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:112:16, :137:29, :145:31]
    .io_req_bits_prv               (io_ptw_status_prv),
    .io_resp_miss                  (_tlb_io_resp_miss),
    .io_resp_paddr                 (_tlb_io_resp_paddr),
    .io_resp_pf_inst               (_tlb_io_resp_pf_inst),
    .io_resp_ae_inst               (_tlb_io_resp_ae_inst),
    .io_sfence_valid               (io_cpu_sfence_valid),
    .io_sfence_bits_rs1            (io_cpu_sfence_bits_rs1),
    .io_sfence_bits_rs2            (io_cpu_sfence_bits_rs2),
    .io_sfence_bits_addr           (io_cpu_sfence_bits_addr),
    .io_ptw_req_ready              (io_ptw_req_ready),
    .io_ptw_req_valid              (io_ptw_req_valid),
    .io_ptw_req_bits_bits_addr     (io_ptw_req_bits_bits_addr),
    .io_ptw_req_bits_bits_need_gpa (io_ptw_req_bits_bits_need_gpa),
    .io_ptw_resp_valid             (io_ptw_resp_valid),
    .io_ptw_resp_bits_ae_ptw       (io_ptw_resp_bits_ae_ptw),
    .io_ptw_resp_bits_ae_final     (io_ptw_resp_bits_ae_final),
    .io_ptw_resp_bits_pf           (io_ptw_resp_bits_pf),
    .io_ptw_resp_bits_gf           (io_ptw_resp_bits_gf),
    .io_ptw_resp_bits_hr           (io_ptw_resp_bits_hr),
    .io_ptw_resp_bits_hw           (io_ptw_resp_bits_hw),
    .io_ptw_resp_bits_hx           (io_ptw_resp_bits_hx),
    .io_ptw_resp_bits_pte_ppn      (io_ptw_resp_bits_pte_ppn),
    .io_ptw_resp_bits_pte_d        (io_ptw_resp_bits_pte_d),
    .io_ptw_resp_bits_pte_a        (io_ptw_resp_bits_pte_a),
    .io_ptw_resp_bits_pte_g        (io_ptw_resp_bits_pte_g),
    .io_ptw_resp_bits_pte_u        (io_ptw_resp_bits_pte_u),
    .io_ptw_resp_bits_pte_x        (io_ptw_resp_bits_pte_x),
    .io_ptw_resp_bits_pte_w        (io_ptw_resp_bits_pte_w),
    .io_ptw_resp_bits_pte_r        (io_ptw_resp_bits_pte_r),
    .io_ptw_resp_bits_pte_v        (io_ptw_resp_bits_pte_v),
    .io_ptw_resp_bits_level        (io_ptw_resp_bits_level),
    .io_ptw_resp_bits_homogeneous  (io_ptw_resp_bits_homogeneous),
    .io_ptw_ptbr_mode              (io_ptw_ptbr_mode),
    .io_ptw_status_debug           (io_ptw_status_debug)
  );
  ShuttleBTB btb (	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:109:19]
    .clock                                 (clock),
    .reset                                 (reset),
    .io_req_bits_addr                      ({s1_vpc[38:3], 3'h0}),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:125:29, :137:29, :155:24]
    .io_resp_valid                         (_btb_io_resp_valid),
    .io_resp_bits_taken                    (_btb_io_resp_bits_taken),
    .io_resp_bits_bridx                    (_btb_io_resp_bits_bridx),
    .io_resp_bits_target                   (_btb_io_resp_bits_target),
    .io_resp_bits_entry                    (_btb_io_resp_bits_entry),
    .io_resp_bits_bht_history              (_btb_io_resp_bits_bht_history),
    .io_resp_bits_bht_value                (_btb_io_resp_bits_bht_value),
    .io_btb_update_valid                   (io_cpu_btb_update_valid),
    .io_btb_update_bits_prediction_entry   (io_cpu_btb_update_bits_prediction_entry),
    .io_btb_update_bits_pc                 (io_cpu_btb_update_bits_pc),
    .io_btb_update_bits_target             (io_cpu_btb_update_bits_target),
    .io_btb_update_bits_isValid            (io_cpu_btb_update_bits_isValid),
    .io_btb_update_bits_br_pc              (io_cpu_btb_update_bits_br_pc),
    .io_btb_update_bits_cfiType            (io_cpu_btb_update_bits_cfiType),
    .io_btb_update_bits_mispredict         (io_cpu_btb_update_bits_mispredict),
    .io_bht_update_valid                   (io_cpu_bht_update_valid),
    .io_bht_update_bits_prediction_history (io_cpu_bht_update_bits_prediction_history),
    .io_bht_update_bits_pc                 (io_cpu_bht_update_bits_pc),
    .io_bht_update_bits_branch             (io_cpu_bht_update_bits_branch),
    .io_bht_update_bits_taken              (io_cpu_bht_update_bits_taken),
    .io_bht_update_bits_mispredict         (io_cpu_bht_update_bits_mispredict),
    .io_flush                              (_valid_T_18 & s2_btb_resp_valid & (&s2_btb_resp_bits_bridx) | _valid_T_9 & s2_btb_resp_valid & _redir_br_T_16 | ~valid_1 & s2_btb_resp_valid & _redir_br_T_9)	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:194:28, :269:{11,39,65,74}, :270:20, :304:32, :310:76, :316:36]
  );
  RVCExpander expanded_rvc_exp (	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25]
    .io_in       (_expanded_T_1),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:288:37]
    .io_out_bits (_expanded_rvc_exp_io_out_bits),
    .io_rvc      (_expanded_rvc_exp_io_rvc)
  );
  RVCExpander expanded_rvc_exp_1 (	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25]
    .io_in       (_icache_io_resp_bits[31:0]),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :293:45]
    .io_out_bits (_expanded_rvc_exp_1_io_out_bits),
    .io_rvc      (_expanded_rvc_exp_1_io_rvc)
  );
  RVCExpander expanded_rvc_exp_2 (	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25]
    .io_in       (_icache_io_resp_bits[47:16]),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :300:29]
    .io_out_bits (_expanded_rvc_exp_2_io_out_bits),
    .io_rvc      (_expanded_rvc_exp_2_io_rvc)
  );
  RVCExpander expanded_rvc_exp_3 (	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25]
    .io_in       (_icache_io_resp_bits[63:32]),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :312:29]
    .io_out_bits (_expanded_rvc_exp_3_io_out_bits),
    .io_rvc      (_expanded_rvc_exp_3_io_rvc)
  );
  RVCExpander expanded_rvc_exp_4 (	// @[generators/shuttle/src/main/scala/common/Consts.scala:41:25]
    .io_in       (f2_fetch_bundle_insts_3),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:306:21]
    .io_out_bits (_expanded_rvc_exp_4_io_out_bits),
    .io_rvc      (_expanded_rvc_exp_4_io_rvc)
  );
  ShuttleFetchBuffer fb (	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:346:18]
    .clock                                   (clock),
    .reset                                   (reset),
    .io_enq_ready                            (_fb_io_enq_ready),
    .io_enq_valid                            (s2_valid & ~f2_clear & (_icache_io_resp_valid | _fb_io_enq_valid_T_2 & ~s2_tlb_miss)),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :185:25, :191:28, :193:50, :347:{35,45}, :348:{27,76,79}, :356:32, :370:24, :374:17]
    .io_enq_bits_next_pc_valid               (f2_fetch_bundle_next_pc_valid),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:280:18, :281:22]
    .io_enq_bits_next_pc_bits                (f2_fetch_bundle_next_pc_bits),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:213:32]
    .io_enq_bits_edge_inst                   (f2_prev_is_half),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:242:32]
    .io_enq_bits_insts_0                     (f2_fetch_bundle_insts_0),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:287:30, :289:38, :294:38]
    .io_enq_bits_insts_1                     (_icache_io_resp_bits[47:16]),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :300:29]
    .io_enq_bits_insts_2                     (_icache_io_resp_bits[63:32]),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:58:26, :312:29]
    .io_enq_bits_insts_3                     (f2_fetch_bundle_insts_3),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:306:21]
    .io_enq_bits_exp_insts_0                 (f2_fetch_bundle_exp_insts_0),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:287:30, :290:38, :295:38]
    .io_enq_bits_exp_insts_1                 (f2_fetch_bundle_exp_insts_1),	// @[generators/shuttle/src/main/scala/common/Consts.scala:43:8]
    .io_enq_bits_exp_insts_2                 (f2_fetch_bundle_exp_insts_2),	// @[generators/shuttle/src/main/scala/common/Consts.scala:43:8]
    .io_enq_bits_exp_insts_3                 (f2_fetch_bundle_exp_insts_3),	// @[generators/shuttle/src/main/scala/common/Consts.scala:43:8]
    .io_enq_bits_pcs_0                       (_GEN_0 - {38'h0, f2_prev_is_half, 1'h0}),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:112:16, :229:39, :242:32, :268:58]
    .io_enq_bits_pcs_1                       (_GEN_0 + 40'h2),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:229:39, :268:45]
    .io_enq_bits_pcs_2                       (_GEN_0 + 40'h4),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:229:39, :268:45]
    .io_enq_bits_pcs_3                       (_GEN_0 + 40'h6),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:229:39, :268:45]
    .io_enq_bits_mask                        ({f2_inst_mask_3, f2_inst_mask_2, f2_inst_mask_1, f2_inst_mask_0}),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:251:46, :267:{33,62}]
    .io_enq_bits_btb_resp_valid              (s2_btb_resp_valid),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:194:28]
    .io_enq_bits_btb_resp_bits_entry         (s2_btb_resp_bits_entry),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:194:28]
    .io_enq_bits_btb_resp_bits_bht_history   (s2_btb_resp_bits_bht_history),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:194:28]
    .io_enq_bits_ras_head                    (s2_ras_head),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:188:28]
    .io_enq_bits_xcpt_pf_if                  (s2_tlb_resp_pf_inst),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:190:28]
    .io_enq_bits_xcpt_ae_if                  (s2_tlb_resp_ae_inst),	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:190:28]
    .io_deq_0_ready                          (io_cpu_resp_0_ready),
    .io_deq_0_valid                          (io_cpu_resp_0_valid),
    .io_deq_0_bits_inst                      (io_cpu_resp_0_bits_inst),
    .io_deq_0_bits_raw_inst                  (io_cpu_resp_0_bits_raw_inst),
    .io_deq_0_bits_pc                        (io_cpu_resp_0_bits_pc),
    .io_deq_0_bits_edge_inst                 (io_cpu_resp_0_bits_edge_inst),
    .io_deq_0_bits_rvc                       (io_cpu_resp_0_bits_rvc),
    .io_deq_0_bits_btb_resp_valid            (io_cpu_resp_0_bits_btb_resp_valid),
    .io_deq_0_bits_btb_resp_bits_entry       (io_cpu_resp_0_bits_btb_resp_bits_entry),
    .io_deq_0_bits_btb_resp_bits_bht_history (io_cpu_resp_0_bits_btb_resp_bits_bht_history),
    .io_deq_0_bits_sfb_br                    (io_cpu_resp_0_bits_sfb_br),
    .io_deq_0_bits_next_pc_valid             (io_cpu_resp_0_bits_next_pc_valid),
    .io_deq_0_bits_next_pc_bits              (io_cpu_resp_0_bits_next_pc_bits),
    .io_deq_0_bits_ras_head                  (io_cpu_resp_0_bits_ras_head),
    .io_deq_0_bits_xcpt                      (io_cpu_resp_0_bits_xcpt),
    .io_deq_0_bits_xcpt_cause                (io_cpu_resp_0_bits_xcpt_cause),
    .io_deq_0_bits_mem_size                  (io_cpu_resp_0_bits_mem_size),
    .io_deq_1_ready                          (io_cpu_resp_1_ready),
    .io_deq_1_valid                          (io_cpu_resp_1_valid),
    .io_deq_1_bits_inst                      (io_cpu_resp_1_bits_inst),
    .io_deq_1_bits_raw_inst                  (io_cpu_resp_1_bits_raw_inst),
    .io_deq_1_bits_pc                        (io_cpu_resp_1_bits_pc),
    .io_deq_1_bits_edge_inst                 (io_cpu_resp_1_bits_edge_inst),
    .io_deq_1_bits_rvc                       (io_cpu_resp_1_bits_rvc),
    .io_deq_1_bits_btb_resp_valid            (io_cpu_resp_1_bits_btb_resp_valid),
    .io_deq_1_bits_btb_resp_bits_entry       (io_cpu_resp_1_bits_btb_resp_bits_entry),
    .io_deq_1_bits_btb_resp_bits_bht_history (io_cpu_resp_1_bits_btb_resp_bits_bht_history),
    .io_deq_1_bits_sfb_br                    (io_cpu_resp_1_bits_sfb_br),
    .io_deq_1_bits_next_pc_valid             (io_cpu_resp_1_bits_next_pc_valid),
    .io_deq_1_bits_next_pc_bits              (io_cpu_resp_1_bits_next_pc_bits),
    .io_deq_1_bits_ras_head                  (io_cpu_resp_1_bits_ras_head),
    .io_deq_1_bits_xcpt                      (io_cpu_resp_1_bits_xcpt),
    .io_deq_1_bits_xcpt_cause                (io_cpu_resp_1_bits_xcpt_cause),
    .io_deq_1_bits_mem_size                  (io_cpu_resp_1_bits_mem_size),
    .io_clear                                (f2_clear)	// @[generators/shuttle/src/main/scala/ifu/Frontend.scala:356:32, :370:24, :374:17]
  );
endmodule

