// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module RegisterFile(	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:120:7]
  input          clock,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:120:7]
  input          reset,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:120:7]
  output         io_read_2_0_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_2_0_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_read_2_0_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_2_0_req_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output [127:0] io_read_2_0_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_read_2_1_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_2_1_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_read_2_1_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_2_1_req_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output [127:0] io_read_2_1_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_read_2_2_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_2_2_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_read_2_2_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_2_2_req_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output [127:0] io_read_2_2_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_read_1_0_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_1_0_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_read_1_0_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_1_0_req_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output [127:0] io_read_1_0_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_read_1_1_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_1_1_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_read_1_1_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_1_1_req_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output [127:0] io_read_1_1_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_read_0_0_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_0_0_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_read_0_0_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_0_0_req_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output [127:0] io_read_0_0_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_read_0_1_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_0_1_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_read_0_1_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_0_1_req_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output [127:0] io_read_0_1_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_read_0_2_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_0_2_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_read_0_2_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_0_2_req_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output [127:0] io_read_0_2_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_read_0_3_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_read_0_3_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_read_0_3_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output [127:0] io_read_0_3_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_mask_read_0_0_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_mask_read_0_0_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_mask_read_0_0_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_mask_read_0_0_req_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output [127:0] io_mask_read_0_0_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_mask_read_0_1_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_mask_read_0_1_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_mask_read_0_1_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_mask_read_0_1_req_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output [127:0] io_mask_read_0_1_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_mask_read_0_2_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_mask_read_0_2_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_mask_read_0_2_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_mask_read_0_2_req_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output [127:0] io_mask_read_0_2_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_mask_read_0_3_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_mask_read_0_3_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_mask_read_0_3_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_mask_read_0_3_req_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output [127:0] io_mask_read_0_3_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_mask_read_0_4_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_mask_read_0_4_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_mask_read_0_4_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_mask_read_0_4_req_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output [127:0] io_mask_read_0_4_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_mask_read_0_5_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_mask_read_0_5_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_mask_read_0_5_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output [127:0] io_mask_read_0_5_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_pipe_writes_0_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_pipe_writes_0_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [127:0] io_pipe_writes_0_bits_data,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [127:0] io_pipe_writes_0_bits_mask,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_pipe_writes_1_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_pipe_writes_1_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [127:0] io_pipe_writes_1_bits_data,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [127:0] io_pipe_writes_1_bits_mask,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_ll_writes_0_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_ll_writes_0_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_ll_writes_0_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [127:0] io_ll_writes_0_bits_data,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [127:0] io_ll_writes_0_bits_mask,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_ll_writes_1_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_ll_writes_1_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_ll_writes_2_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_ll_writes_2_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_ll_writes_2_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [127:0] io_ll_writes_2_bits_data,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [127:0] io_ll_writes_2_bits_mask,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  output         io_ll_writes_3_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input          io_ll_writes_3_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [5:0]   io_ll_writes_3_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [127:0] io_ll_writes_3_bits_data,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
  input  [127:0] io_ll_writes_3_bits_mask	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14]
);

  wire         _ll_arb_3_io_in_0_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire         _ll_arb_3_io_in_2_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire         _ll_arb_3_io_in_3_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire         _ll_arb_3_io_out_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire [5:0]   _ll_arb_3_io_out_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire [127:0] _ll_arb_3_io_out_bits_data;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire [127:0] _ll_arb_3_io_out_bits_mask;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire         _ll_arb_2_io_in_0_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire         _ll_arb_2_io_in_2_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire         _ll_arb_2_io_in_3_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire         _ll_arb_2_io_out_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire [5:0]   _ll_arb_2_io_out_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire [127:0] _ll_arb_2_io_out_bits_data;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire [127:0] _ll_arb_2_io_out_bits_mask;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire         _ll_arb_1_io_in_0_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire         _ll_arb_1_io_in_2_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire         _ll_arb_1_io_in_3_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire         _ll_arb_1_io_out_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire [5:0]   _ll_arb_1_io_out_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire [127:0] _ll_arb_1_io_out_bits_data;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire [127:0] _ll_arb_1_io_out_bits_mask;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire         _ll_arb_io_in_0_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire         _ll_arb_io_in_2_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire         _ll_arb_io_in_3_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire         _ll_arb_io_out_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire [5:0]   _ll_arb_io_out_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire [127:0] _ll_arb_io_out_bits_data;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire [127:0] _ll_arb_io_out_bits_mask;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  wire [5:0]   _mask_xbar_io_out_0_req_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:145:27]
  wire [5:0]   _mask_xbar_io_out_1_req_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:145:27]
  wire [5:0]   _mask_xbar_io_out_2_req_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:145:27]
  wire [5:0]   _mask_xbar_io_out_3_req_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:145:27]
  wire         _xbar_2_io_out_0_req_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire [5:0]   _xbar_2_io_out_0_req_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire         _xbar_2_io_out_1_req_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire [5:0]   _xbar_2_io_out_1_req_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire         _xbar_2_io_out_2_req_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire [5:0]   _xbar_2_io_out_2_req_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire         _xbar_2_io_out_3_req_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire [5:0]   _xbar_2_io_out_3_req_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire         _xbar_1_io_out_0_req_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire [5:0]   _xbar_1_io_out_0_req_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire         _xbar_1_io_out_1_req_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire [5:0]   _xbar_1_io_out_1_req_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire         _xbar_1_io_out_2_req_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire [5:0]   _xbar_1_io_out_2_req_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire         _xbar_1_io_out_3_req_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire [5:0]   _xbar_1_io_out_3_req_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire         _xbar_io_out_0_req_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire [5:0]   _xbar_io_out_0_req_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire         _xbar_io_out_1_req_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire [5:0]   _xbar_io_out_1_req_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire         _xbar_io_out_2_req_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire [5:0]   _xbar_io_out_2_req_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire         _xbar_io_out_3_req_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire [5:0]   _xbar_io_out_3_req_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
  wire         _vrf_3_io_read_0_req_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire [127:0] _vrf_3_io_read_0_resp;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_3_io_read_1_req_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire [127:0] _vrf_3_io_read_1_resp;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_3_io_read_2_req_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire [127:0] _vrf_3_io_read_2_resp;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_3_io_mask_read_0_req_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire [127:0] _vrf_3_io_mask_read_0_resp;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_3_io_ll_write_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_2_io_read_0_req_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire [127:0] _vrf_2_io_read_0_resp;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_2_io_read_1_req_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire [127:0] _vrf_2_io_read_1_resp;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_2_io_read_2_req_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire [127:0] _vrf_2_io_read_2_resp;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_2_io_mask_read_0_req_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire [127:0] _vrf_2_io_mask_read_0_resp;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_2_io_ll_write_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_1_io_read_0_req_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire [127:0] _vrf_1_io_read_0_resp;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_1_io_read_1_req_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire [127:0] _vrf_1_io_read_1_resp;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_1_io_read_2_req_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire [127:0] _vrf_1_io_read_2_resp;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_1_io_mask_read_0_req_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire [127:0] _vrf_1_io_mask_read_0_resp;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_1_io_ll_write_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_0_io_read_0_req_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire [127:0] _vrf_0_io_read_0_resp;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_0_io_read_1_req_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire [127:0] _vrf_0_io_read_1_resp;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_0_io_read_2_req_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire [127:0] _vrf_0_io_read_2_resp;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_0_io_mask_read_0_req_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire [127:0] _vrf_0_io_mask_read_0_resp;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         _vrf_0_io_ll_write_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  wire         bank_match_0 = io_pipe_writes_0_bits_eg[1:0] == 2'h0 & io_pipe_writes_0_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:{63,72}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
  wire         bank_match_1 = io_pipe_writes_1_bits_eg[1:0] == 2'h0 & io_pipe_writes_1_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:{63,72}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
  wire [5:0]   _GEN = {2'h0, io_ll_writes_0_bits_eg[5:2]};	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:63, :172:{33,46}]
  wire [5:0]   _GEN_0 = {2'h0, io_ll_writes_1_bits_eg[5:2]};	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:63, :172:{33,46}]
  wire [5:0]   _GEN_1 = {2'h0, io_ll_writes_2_bits_eg[5:2]};	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:63, :172:{33,46}]
  wire [5:0]   _GEN_2 = {2'h0, io_ll_writes_3_bits_eg[5:2]};	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:63, :172:{33,46}]
  wire         bank_match_0_1 = io_pipe_writes_0_bits_eg[1:0] == 2'h1 & io_pipe_writes_0_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:{63,72}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
  wire         bank_match_1_1 = io_pipe_writes_1_bits_eg[1:0] == 2'h1 & io_pipe_writes_1_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:{63,72}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
  wire         bank_match_0_2 = io_pipe_writes_0_bits_eg[1:0] == 2'h2 & io_pipe_writes_0_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:{63,72}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
  wire         bank_match_1_2 = io_pipe_writes_1_bits_eg[1:0] == 2'h2 & io_pipe_writes_1_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:{63,72}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
  wire         bank_match_0_3 = (&(io_pipe_writes_0_bits_eg[1:0])) & io_pipe_writes_0_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:{63,72}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
  wire         bank_match_1_3 = (&(io_pipe_writes_1_bits_eg[1:0])) & io_pipe_writes_1_valid;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:{63,72}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
  RegisterFileBank vrf_0 (	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .clock                      (clock),
    .reset                      (reset),
    .io_read_0_req_ready        (_vrf_0_io_read_0_req_ready),
    .io_read_0_req_valid        (_xbar_io_out_0_req_valid),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_0_req_bits_eg      (_xbar_io_out_0_req_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_0_resp             (_vrf_0_io_read_0_resp),
    .io_read_1_req_ready        (_vrf_0_io_read_1_req_ready),
    .io_read_1_req_valid        (_xbar_1_io_out_0_req_valid),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_1_req_bits_eg      (_xbar_1_io_out_0_req_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_1_resp             (_vrf_0_io_read_1_resp),
    .io_read_2_req_ready        (_vrf_0_io_read_2_req_ready),
    .io_read_2_req_valid        (_xbar_2_io_out_0_req_valid),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_2_req_bits_eg      (_xbar_2_io_out_0_req_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_2_resp             (_vrf_0_io_read_2_resp),
    .io_mask_read_0_req_ready   (_vrf_0_io_mask_read_0_req_ready),
    .io_mask_read_0_req_bits_eg (_mask_xbar_io_out_0_req_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:145:27]
    .io_mask_read_0_resp        (_vrf_0_io_mask_read_0_resp),
    .io_write_valid             (bank_match_0 | bank_match_1),	// @[generators/rocket-chip/src/main/scala/util/package.scala:81:59, generators/saturn/src/main/scala/backend/RegisterFile.scala:155:72]
    .io_write_bits_eg           ({2'h0, (bank_match_0 ? io_pipe_writes_0_bits_eg[5:2] : 4'h0) | (bank_match_1 ? io_pipe_writes_1_bits_eg[5:2] : 4'h0)}),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14, :155:{63,72}, :164:25, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_write_bits_data         ((bank_match_0 ? io_pipe_writes_0_bits_data : 128'h0) | (bank_match_1 ? io_pipe_writes_1_bits_data : 128'h0)),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:72, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_write_bits_mask         ((bank_match_0 ? io_pipe_writes_0_bits_mask : 128'h0) | (bank_match_1 ? io_pipe_writes_1_bits_mask : 128'h0)),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:72, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_ll_write_ready          (_vrf_0_io_ll_write_ready),
    .io_ll_write_valid          (_ll_arb_io_out_valid),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
    .io_ll_write_bits_eg        (_ll_arb_io_out_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
    .io_ll_write_bits_data      (_ll_arb_io_out_bits_data),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
    .io_ll_write_bits_mask      (_ll_arb_io_out_bits_mask)	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  );
  RegisterFileBank vrf_1 (	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .clock                      (clock),
    .reset                      (reset),
    .io_read_0_req_ready        (_vrf_1_io_read_0_req_ready),
    .io_read_0_req_valid        (_xbar_io_out_1_req_valid),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_0_req_bits_eg      (_xbar_io_out_1_req_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_0_resp             (_vrf_1_io_read_0_resp),
    .io_read_1_req_ready        (_vrf_1_io_read_1_req_ready),
    .io_read_1_req_valid        (_xbar_1_io_out_1_req_valid),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_1_req_bits_eg      (_xbar_1_io_out_1_req_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_1_resp             (_vrf_1_io_read_1_resp),
    .io_read_2_req_ready        (_vrf_1_io_read_2_req_ready),
    .io_read_2_req_valid        (_xbar_2_io_out_1_req_valid),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_2_req_bits_eg      (_xbar_2_io_out_1_req_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_2_resp             (_vrf_1_io_read_2_resp),
    .io_mask_read_0_req_ready   (_vrf_1_io_mask_read_0_req_ready),
    .io_mask_read_0_req_bits_eg (_mask_xbar_io_out_1_req_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:145:27]
    .io_mask_read_0_resp        (_vrf_1_io_mask_read_0_resp),
    .io_write_valid             (bank_match_0_1 | bank_match_1_1),	// @[generators/rocket-chip/src/main/scala/util/package.scala:81:59, generators/saturn/src/main/scala/backend/RegisterFile.scala:155:72]
    .io_write_bits_eg           ({2'h0, (bank_match_0_1 ? io_pipe_writes_0_bits_eg[5:2] : 4'h0) | (bank_match_1_1 ? io_pipe_writes_1_bits_eg[5:2] : 4'h0)}),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14, :155:{63,72}, :164:25, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_write_bits_data         ((bank_match_0_1 ? io_pipe_writes_0_bits_data : 128'h0) | (bank_match_1_1 ? io_pipe_writes_1_bits_data : 128'h0)),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:72, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_write_bits_mask         ((bank_match_0_1 ? io_pipe_writes_0_bits_mask : 128'h0) | (bank_match_1_1 ? io_pipe_writes_1_bits_mask : 128'h0)),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:72, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_ll_write_ready          (_vrf_1_io_ll_write_ready),
    .io_ll_write_valid          (_ll_arb_1_io_out_valid),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
    .io_ll_write_bits_eg        (_ll_arb_1_io_out_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
    .io_ll_write_bits_data      (_ll_arb_1_io_out_bits_data),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
    .io_ll_write_bits_mask      (_ll_arb_1_io_out_bits_mask)	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  );
  RegisterFileBank vrf_2 (	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .clock                      (clock),
    .reset                      (reset),
    .io_read_0_req_ready        (_vrf_2_io_read_0_req_ready),
    .io_read_0_req_valid        (_xbar_io_out_2_req_valid),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_0_req_bits_eg      (_xbar_io_out_2_req_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_0_resp             (_vrf_2_io_read_0_resp),
    .io_read_1_req_ready        (_vrf_2_io_read_1_req_ready),
    .io_read_1_req_valid        (_xbar_1_io_out_2_req_valid),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_1_req_bits_eg      (_xbar_1_io_out_2_req_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_1_resp             (_vrf_2_io_read_1_resp),
    .io_read_2_req_ready        (_vrf_2_io_read_2_req_ready),
    .io_read_2_req_valid        (_xbar_2_io_out_2_req_valid),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_2_req_bits_eg      (_xbar_2_io_out_2_req_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_2_resp             (_vrf_2_io_read_2_resp),
    .io_mask_read_0_req_ready   (_vrf_2_io_mask_read_0_req_ready),
    .io_mask_read_0_req_bits_eg (_mask_xbar_io_out_2_req_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:145:27]
    .io_mask_read_0_resp        (_vrf_2_io_mask_read_0_resp),
    .io_write_valid             (bank_match_0_2 | bank_match_1_2),	// @[generators/rocket-chip/src/main/scala/util/package.scala:81:59, generators/saturn/src/main/scala/backend/RegisterFile.scala:155:72]
    .io_write_bits_eg           ({2'h0, (bank_match_0_2 ? io_pipe_writes_0_bits_eg[5:2] : 4'h0) | (bank_match_1_2 ? io_pipe_writes_1_bits_eg[5:2] : 4'h0)}),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14, :155:{63,72}, :164:25, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_write_bits_data         ((bank_match_0_2 ? io_pipe_writes_0_bits_data : 128'h0) | (bank_match_1_2 ? io_pipe_writes_1_bits_data : 128'h0)),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:72, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_write_bits_mask         ((bank_match_0_2 ? io_pipe_writes_0_bits_mask : 128'h0) | (bank_match_1_2 ? io_pipe_writes_1_bits_mask : 128'h0)),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:72, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_ll_write_ready          (_vrf_2_io_ll_write_ready),
    .io_ll_write_valid          (_ll_arb_2_io_out_valid),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
    .io_ll_write_bits_eg        (_ll_arb_2_io_out_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
    .io_ll_write_bits_data      (_ll_arb_2_io_out_bits_data),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
    .io_ll_write_bits_mask      (_ll_arb_2_io_out_bits_mask)	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  );
  RegisterFileBank vrf_3 (	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .clock                      (clock),
    .reset                      (reset),
    .io_read_0_req_ready        (_vrf_3_io_read_0_req_ready),
    .io_read_0_req_valid        (_xbar_io_out_3_req_valid),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_0_req_bits_eg      (_xbar_io_out_3_req_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_0_resp             (_vrf_3_io_read_0_resp),
    .io_read_1_req_ready        (_vrf_3_io_read_1_req_ready),
    .io_read_1_req_valid        (_xbar_1_io_out_3_req_valid),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_1_req_bits_eg      (_xbar_1_io_out_3_req_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_1_resp             (_vrf_3_io_read_1_resp),
    .io_read_2_req_ready        (_vrf_3_io_read_2_req_ready),
    .io_read_2_req_valid        (_xbar_2_io_out_3_req_valid),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_2_req_bits_eg      (_xbar_2_io_out_3_req_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .io_read_2_resp             (_vrf_3_io_read_2_resp),
    .io_mask_read_0_req_ready   (_vrf_3_io_mask_read_0_req_ready),
    .io_mask_read_0_req_bits_eg (_mask_xbar_io_out_3_req_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:145:27]
    .io_mask_read_0_resp        (_vrf_3_io_mask_read_0_resp),
    .io_write_valid             (bank_match_0_3 | bank_match_1_3),	// @[generators/rocket-chip/src/main/scala/util/package.scala:81:59, generators/saturn/src/main/scala/backend/RegisterFile.scala:155:72]
    .io_write_bits_eg           ({2'h0, (bank_match_0_3 ? io_pipe_writes_0_bits_eg[5:2] : 4'h0) | (bank_match_1_3 ? io_pipe_writes_1_bits_eg[5:2] : 4'h0)}),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:126:14, :155:{63,72}, :164:25, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_write_bits_data         ((bank_match_0_3 ? io_pipe_writes_0_bits_data : 128'h0) | (bank_match_1_3 ? io_pipe_writes_1_bits_data : 128'h0)),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:72, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_write_bits_mask         ((bank_match_0_3 ? io_pipe_writes_0_bits_mask : 128'h0) | (bank_match_1_3 ? io_pipe_writes_1_bits_mask : 128'h0)),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:72, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_ll_write_ready          (_vrf_3_io_ll_write_ready),
    .io_ll_write_valid          (_ll_arb_3_io_out_valid),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
    .io_ll_write_bits_eg        (_ll_arb_3_io_out_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
    .io_ll_write_bits_data      (_ll_arb_3_io_out_bits_data),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
    .io_ll_write_bits_mask      (_ll_arb_3_io_out_bits_mask)	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
  );
  RegisterReadXbar xbar (	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .clock                   (clock),
    .io_in_0_req_ready       (io_read_0_0_req_ready),
    .io_in_0_req_valid       (io_read_0_0_req_valid),
    .io_in_0_req_bits_eg     (io_read_0_0_req_bits_eg),
    .io_in_0_req_bits_oldest (io_read_0_0_req_bits_oldest),
    .io_in_0_resp            (io_read_0_0_resp),
    .io_in_1_req_ready       (io_read_0_1_req_ready),
    .io_in_1_req_valid       (io_read_0_1_req_valid),
    .io_in_1_req_bits_eg     (io_read_0_1_req_bits_eg),
    .io_in_1_req_bits_oldest (io_read_0_1_req_bits_oldest),
    .io_in_1_resp            (io_read_0_1_resp),
    .io_in_2_req_ready       (io_read_0_2_req_ready),
    .io_in_2_req_valid       (io_read_0_2_req_valid),
    .io_in_2_req_bits_eg     (io_read_0_2_req_bits_eg),
    .io_in_2_req_bits_oldest (io_read_0_2_req_bits_oldest),
    .io_in_2_resp            (io_read_0_2_resp),
    .io_in_3_req_ready       (io_read_0_3_req_ready),
    .io_in_3_req_valid       (io_read_0_3_req_valid),
    .io_in_3_req_bits_eg     (io_read_0_3_req_bits_eg),
    .io_in_3_resp            (io_read_0_3_resp),
    .io_out_0_req_ready      (_vrf_0_io_read_0_req_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_0_req_valid      (_xbar_io_out_0_req_valid),
    .io_out_0_req_bits_eg    (_xbar_io_out_0_req_bits_eg),
    .io_out_0_resp           (_vrf_0_io_read_0_resp),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_1_req_ready      (_vrf_1_io_read_0_req_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_1_req_valid      (_xbar_io_out_1_req_valid),
    .io_out_1_req_bits_eg    (_xbar_io_out_1_req_bits_eg),
    .io_out_1_resp           (_vrf_1_io_read_0_resp),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_2_req_ready      (_vrf_2_io_read_0_req_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_2_req_valid      (_xbar_io_out_2_req_valid),
    .io_out_2_req_bits_eg    (_xbar_io_out_2_req_bits_eg),
    .io_out_2_resp           (_vrf_2_io_read_0_resp),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_3_req_ready      (_vrf_3_io_read_0_req_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_3_req_valid      (_xbar_io_out_3_req_valid),
    .io_out_3_req_bits_eg    (_xbar_io_out_3_req_bits_eg),
    .io_out_3_resp           (_vrf_3_io_read_0_resp)	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  );
  RegisterReadXbar_1 xbar_1 (	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .clock                   (clock),
    .io_in_0_req_ready       (io_read_1_0_req_ready),
    .io_in_0_req_valid       (io_read_1_0_req_valid),
    .io_in_0_req_bits_eg     (io_read_1_0_req_bits_eg),
    .io_in_0_req_bits_oldest (io_read_1_0_req_bits_oldest),
    .io_in_0_resp            (io_read_1_0_resp),
    .io_in_1_req_ready       (io_read_1_1_req_ready),
    .io_in_1_req_valid       (io_read_1_1_req_valid),
    .io_in_1_req_bits_eg     (io_read_1_1_req_bits_eg),
    .io_in_1_req_bits_oldest (io_read_1_1_req_bits_oldest),
    .io_in_1_resp            (io_read_1_1_resp),
    .io_out_0_req_ready      (_vrf_0_io_read_1_req_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_0_req_valid      (_xbar_1_io_out_0_req_valid),
    .io_out_0_req_bits_eg    (_xbar_1_io_out_0_req_bits_eg),
    .io_out_0_resp           (_vrf_0_io_read_1_resp),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_1_req_ready      (_vrf_1_io_read_1_req_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_1_req_valid      (_xbar_1_io_out_1_req_valid),
    .io_out_1_req_bits_eg    (_xbar_1_io_out_1_req_bits_eg),
    .io_out_1_resp           (_vrf_1_io_read_1_resp),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_2_req_ready      (_vrf_2_io_read_1_req_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_2_req_valid      (_xbar_1_io_out_2_req_valid),
    .io_out_2_req_bits_eg    (_xbar_1_io_out_2_req_bits_eg),
    .io_out_2_resp           (_vrf_2_io_read_1_resp),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_3_req_ready      (_vrf_3_io_read_1_req_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_3_req_valid      (_xbar_1_io_out_3_req_valid),
    .io_out_3_req_bits_eg    (_xbar_1_io_out_3_req_bits_eg),
    .io_out_3_resp           (_vrf_3_io_read_1_resp)	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  );
  RegisterReadXbar_2 xbar_2 (	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:137:22]
    .clock                   (clock),
    .io_in_0_req_ready       (io_read_2_0_req_ready),
    .io_in_0_req_valid       (io_read_2_0_req_valid),
    .io_in_0_req_bits_eg     (io_read_2_0_req_bits_eg),
    .io_in_0_req_bits_oldest (io_read_2_0_req_bits_oldest),
    .io_in_0_resp            (io_read_2_0_resp),
    .io_in_1_req_ready       (io_read_2_1_req_ready),
    .io_in_1_req_valid       (io_read_2_1_req_valid),
    .io_in_1_req_bits_eg     (io_read_2_1_req_bits_eg),
    .io_in_1_req_bits_oldest (io_read_2_1_req_bits_oldest),
    .io_in_1_resp            (io_read_2_1_resp),
    .io_in_2_req_ready       (io_read_2_2_req_ready),
    .io_in_2_req_valid       (io_read_2_2_req_valid),
    .io_in_2_req_bits_eg     (io_read_2_2_req_bits_eg),
    .io_in_2_req_bits_oldest (io_read_2_2_req_bits_oldest),
    .io_in_2_resp            (io_read_2_2_resp),
    .io_out_0_req_ready      (_vrf_0_io_read_2_req_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_0_req_valid      (_xbar_2_io_out_0_req_valid),
    .io_out_0_req_bits_eg    (_xbar_2_io_out_0_req_bits_eg),
    .io_out_0_resp           (_vrf_0_io_read_2_resp),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_1_req_ready      (_vrf_1_io_read_2_req_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_1_req_valid      (_xbar_2_io_out_1_req_valid),
    .io_out_1_req_bits_eg    (_xbar_2_io_out_1_req_bits_eg),
    .io_out_1_resp           (_vrf_1_io_read_2_resp),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_2_req_ready      (_vrf_2_io_read_2_req_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_2_req_valid      (_xbar_2_io_out_2_req_valid),
    .io_out_2_req_bits_eg    (_xbar_2_io_out_2_req_bits_eg),
    .io_out_2_resp           (_vrf_2_io_read_2_resp),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_3_req_ready      (_vrf_3_io_read_2_req_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_3_req_valid      (_xbar_2_io_out_3_req_valid),
    .io_out_3_req_bits_eg    (_xbar_2_io_out_3_req_bits_eg),
    .io_out_3_resp           (_vrf_3_io_read_2_resp)	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  );
  RegisterReadXbar_3 mask_xbar (	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:145:27]
    .clock                   (clock),
    .io_in_0_req_ready       (io_mask_read_0_0_req_ready),
    .io_in_0_req_valid       (io_mask_read_0_0_req_valid),
    .io_in_0_req_bits_eg     (io_mask_read_0_0_req_bits_eg),
    .io_in_0_req_bits_oldest (io_mask_read_0_0_req_bits_oldest),
    .io_in_0_resp            (io_mask_read_0_0_resp),
    .io_in_1_req_ready       (io_mask_read_0_1_req_ready),
    .io_in_1_req_valid       (io_mask_read_0_1_req_valid),
    .io_in_1_req_bits_eg     (io_mask_read_0_1_req_bits_eg),
    .io_in_1_req_bits_oldest (io_mask_read_0_1_req_bits_oldest),
    .io_in_1_resp            (io_mask_read_0_1_resp),
    .io_in_2_req_ready       (io_mask_read_0_2_req_ready),
    .io_in_2_req_valid       (io_mask_read_0_2_req_valid),
    .io_in_2_req_bits_eg     (io_mask_read_0_2_req_bits_eg),
    .io_in_2_req_bits_oldest (io_mask_read_0_2_req_bits_oldest),
    .io_in_2_resp            (io_mask_read_0_2_resp),
    .io_in_3_req_ready       (io_mask_read_0_3_req_ready),
    .io_in_3_req_valid       (io_mask_read_0_3_req_valid),
    .io_in_3_req_bits_eg     (io_mask_read_0_3_req_bits_eg),
    .io_in_3_req_bits_oldest (io_mask_read_0_3_req_bits_oldest),
    .io_in_3_resp            (io_mask_read_0_3_resp),
    .io_in_4_req_ready       (io_mask_read_0_4_req_ready),
    .io_in_4_req_valid       (io_mask_read_0_4_req_valid),
    .io_in_4_req_bits_eg     (io_mask_read_0_4_req_bits_eg),
    .io_in_4_req_bits_oldest (io_mask_read_0_4_req_bits_oldest),
    .io_in_4_resp            (io_mask_read_0_4_resp),
    .io_in_5_req_ready       (io_mask_read_0_5_req_ready),
    .io_in_5_req_valid       (io_mask_read_0_5_req_valid),
    .io_in_5_req_bits_eg     (io_mask_read_0_5_req_bits_eg),
    .io_in_5_resp            (io_mask_read_0_5_resp),
    .io_out_0_req_ready      (_vrf_0_io_mask_read_0_req_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_0_req_bits_eg    (_mask_xbar_io_out_0_req_bits_eg),
    .io_out_0_resp           (_vrf_0_io_mask_read_0_resp),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_1_req_ready      (_vrf_1_io_mask_read_0_req_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_1_req_bits_eg    (_mask_xbar_io_out_1_req_bits_eg),
    .io_out_1_resp           (_vrf_1_io_mask_read_0_resp),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_2_req_ready      (_vrf_2_io_mask_read_0_req_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_2_req_bits_eg    (_mask_xbar_io_out_2_req_bits_eg),
    .io_out_2_resp           (_vrf_2_io_mask_read_0_resp),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_3_req_ready      (_vrf_3_io_mask_read_0_req_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_3_req_bits_eg    (_mask_xbar_io_out_3_req_bits_eg),
    .io_out_3_resp           (_vrf_3_io_mask_read_0_resp)	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
  );
  Arbiter4_VectorWrite ll_arb (	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
    .io_in_0_ready     (_ll_arb_io_in_0_ready),
    .io_in_0_valid     (io_ll_writes_0_valid & ~(|(io_ll_writes_0_bits_eg[1:0]))),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:171:{40,57}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
    .io_in_0_bits_eg   (_GEN),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:172:33]
    .io_in_0_bits_data (io_ll_writes_0_bits_data),
    .io_in_0_bits_mask (io_ll_writes_0_bits_mask),
    .io_in_1_valid     (io_ll_writes_1_valid & io_ll_writes_1_bits_eg[1:0] == 2'h0),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:63, :171:{40,57}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
    .io_in_1_bits_eg   (_GEN_0),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:172:33]
    .io_in_2_ready     (_ll_arb_io_in_2_ready),
    .io_in_2_valid     (io_ll_writes_2_valid & ~(|(io_ll_writes_2_bits_eg[1:0]))),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:171:{40,57}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
    .io_in_2_bits_eg   (_GEN_1),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:172:33]
    .io_in_2_bits_data (io_ll_writes_2_bits_data),
    .io_in_2_bits_mask (io_ll_writes_2_bits_mask),
    .io_in_3_ready     (_ll_arb_io_in_3_ready),
    .io_in_3_valid     (io_ll_writes_3_valid & ~(|(io_ll_writes_3_bits_eg[1:0]))),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:171:{40,57}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
    .io_in_3_bits_eg   (_GEN_2),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:172:33]
    .io_in_3_bits_data (io_ll_writes_3_bits_data),
    .io_in_3_bits_mask (io_ll_writes_3_bits_mask),
    .io_out_ready      (_vrf_0_io_ll_write_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_valid      (_ll_arb_io_out_valid),
    .io_out_bits_eg    (_ll_arb_io_out_bits_eg),
    .io_out_bits_data  (_ll_arb_io_out_bits_data),
    .io_out_bits_mask  (_ll_arb_io_out_bits_mask)
  );
  Arbiter4_VectorWrite ll_arb_1 (	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
    .io_in_0_ready     (_ll_arb_1_io_in_0_ready),
    .io_in_0_valid     (io_ll_writes_0_valid & io_ll_writes_0_bits_eg[1:0] == 2'h1),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:63, :171:{40,57}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
    .io_in_0_bits_eg   (_GEN),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:172:33]
    .io_in_0_bits_data (io_ll_writes_0_bits_data),
    .io_in_0_bits_mask (io_ll_writes_0_bits_mask),
    .io_in_1_valid     (io_ll_writes_1_valid & io_ll_writes_1_bits_eg[1:0] == 2'h1),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:63, :171:{40,57}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
    .io_in_1_bits_eg   (_GEN_0),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:172:33]
    .io_in_2_ready     (_ll_arb_1_io_in_2_ready),
    .io_in_2_valid     (io_ll_writes_2_valid & io_ll_writes_2_bits_eg[1:0] == 2'h1),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:63, :171:{40,57}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
    .io_in_2_bits_eg   (_GEN_1),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:172:33]
    .io_in_2_bits_data (io_ll_writes_2_bits_data),
    .io_in_2_bits_mask (io_ll_writes_2_bits_mask),
    .io_in_3_ready     (_ll_arb_1_io_in_3_ready),
    .io_in_3_valid     (io_ll_writes_3_valid & io_ll_writes_3_bits_eg[1:0] == 2'h1),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:63, :171:{40,57}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
    .io_in_3_bits_eg   (_GEN_2),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:172:33]
    .io_in_3_bits_data (io_ll_writes_3_bits_data),
    .io_in_3_bits_mask (io_ll_writes_3_bits_mask),
    .io_out_ready      (_vrf_1_io_ll_write_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_valid      (_ll_arb_1_io_out_valid),
    .io_out_bits_eg    (_ll_arb_1_io_out_bits_eg),
    .io_out_bits_data  (_ll_arb_1_io_out_bits_data),
    .io_out_bits_mask  (_ll_arb_1_io_out_bits_mask)
  );
  Arbiter4_VectorWrite ll_arb_2 (	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
    .io_in_0_ready     (_ll_arb_2_io_in_0_ready),
    .io_in_0_valid     (io_ll_writes_0_valid & io_ll_writes_0_bits_eg[1:0] == 2'h2),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:63, :171:{40,57}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
    .io_in_0_bits_eg   (_GEN),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:172:33]
    .io_in_0_bits_data (io_ll_writes_0_bits_data),
    .io_in_0_bits_mask (io_ll_writes_0_bits_mask),
    .io_in_1_valid     (io_ll_writes_1_valid & io_ll_writes_1_bits_eg[1:0] == 2'h2),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:63, :171:{40,57}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
    .io_in_1_bits_eg   (_GEN_0),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:172:33]
    .io_in_2_ready     (_ll_arb_2_io_in_2_ready),
    .io_in_2_valid     (io_ll_writes_2_valid & io_ll_writes_2_bits_eg[1:0] == 2'h2),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:63, :171:{40,57}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
    .io_in_2_bits_eg   (_GEN_1),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:172:33]
    .io_in_2_bits_data (io_ll_writes_2_bits_data),
    .io_in_2_bits_mask (io_ll_writes_2_bits_mask),
    .io_in_3_ready     (_ll_arb_2_io_in_3_ready),
    .io_in_3_valid     (io_ll_writes_3_valid & io_ll_writes_3_bits_eg[1:0] == 2'h2),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:155:63, :171:{40,57}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
    .io_in_3_bits_eg   (_GEN_2),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:172:33]
    .io_in_3_bits_data (io_ll_writes_3_bits_data),
    .io_in_3_bits_mask (io_ll_writes_3_bits_mask),
    .io_out_ready      (_vrf_2_io_ll_write_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_valid      (_ll_arb_2_io_out_valid),
    .io_out_bits_eg    (_ll_arb_2_io_out_bits_eg),
    .io_out_bits_data  (_ll_arb_2_io_out_bits_data),
    .io_out_bits_mask  (_ll_arb_2_io_out_bits_mask)
  );
  Arbiter4_VectorWrite ll_arb_3 (	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:167:24]
    .io_in_0_ready     (_ll_arb_3_io_in_0_ready),
    .io_in_0_valid     (io_ll_writes_0_valid & (&(io_ll_writes_0_bits_eg[1:0]))),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:171:{40,57}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
    .io_in_0_bits_eg   (_GEN),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:172:33]
    .io_in_0_bits_data (io_ll_writes_0_bits_data),
    .io_in_0_bits_mask (io_ll_writes_0_bits_mask),
    .io_in_1_valid     (io_ll_writes_1_valid & (&(io_ll_writes_1_bits_eg[1:0]))),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:171:{40,57}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
    .io_in_1_bits_eg   (_GEN_0),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:172:33]
    .io_in_2_ready     (_ll_arb_3_io_in_2_ready),
    .io_in_2_valid     (io_ll_writes_2_valid & (&(io_ll_writes_2_bits_eg[1:0]))),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:171:{40,57}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
    .io_in_2_bits_eg   (_GEN_1),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:172:33]
    .io_in_2_bits_data (io_ll_writes_2_bits_data),
    .io_in_2_bits_mask (io_ll_writes_2_bits_mask),
    .io_in_3_ready     (_ll_arb_3_io_in_3_ready),
    .io_in_3_valid     (io_ll_writes_3_valid & (&(io_ll_writes_3_bits_eg[1:0]))),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:171:{40,57}, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
    .io_in_3_bits_eg   (_GEN_2),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:172:33]
    .io_in_3_bits_data (io_ll_writes_3_bits_data),
    .io_in_3_bits_mask (io_ll_writes_3_bits_mask),
    .io_out_ready      (_vrf_3_io_ll_write_ready),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:134:38]
    .io_out_valid      (_ll_arb_3_io_out_valid),
    .io_out_bits_eg    (_ll_arb_3_io_out_bits_eg),
    .io_out_bits_data  (_ll_arb_3_io_out_bits_data),
    .io_out_bits_mask  (_ll_arb_3_io_out_bits_mask)
  );
  assign io_ll_writes_0_ready = _ll_arb_3_io_in_0_ready & (&(io_ll_writes_0_bits_eg[1:0])) | _ll_arb_2_io_in_0_ready & io_ll_writes_0_bits_eg[1:0] == 2'h2 | _ll_arb_1_io_in_0_ready & io_ll_writes_0_bits_eg[1:0] == 2'h1 | _ll_arb_io_in_0_ready & ~(|(io_ll_writes_0_bits_eg[1:0]));	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:120:7, :155:63, :167:24, :171:57, :175:{35,52,61}, :176:17, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
  assign io_ll_writes_2_ready = _ll_arb_3_io_in_2_ready & (&(io_ll_writes_2_bits_eg[1:0])) | _ll_arb_2_io_in_2_ready & io_ll_writes_2_bits_eg[1:0] == 2'h2 | _ll_arb_1_io_in_2_ready & io_ll_writes_2_bits_eg[1:0] == 2'h1 | _ll_arb_io_in_2_ready & ~(|(io_ll_writes_2_bits_eg[1:0]));	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:120:7, :155:63, :167:24, :171:57, :175:{35,52,61}, :176:17, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
  assign io_ll_writes_3_ready = _ll_arb_3_io_in_3_ready & (&(io_ll_writes_3_bits_eg[1:0])) | _ll_arb_2_io_in_3_ready & io_ll_writes_3_bits_eg[1:0] == 2'h2 | _ll_arb_1_io_in_3_ready & io_ll_writes_3_bits_eg[1:0] == 2'h1 | _ll_arb_io_in_3_ready & ~(|(io_ll_writes_3_bits_eg[1:0]));	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:120:7, :155:63, :167:24, :171:57, :175:{35,52,61}, :176:17, generators/saturn/src/main/scala/common/Bundles.scala:112:49]
endmodule

