// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module SaturatedSumArray(	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7]
  input  [7:0]  io_sum_0,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input  [7:0]  io_sum_1,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input  [7:0]  io_sum_2,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input  [7:0]  io_sum_3,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input  [7:0]  io_sum_4,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input  [7:0]  io_sum_5,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input  [7:0]  io_sum_6,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input  [7:0]  io_sum_7,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input  [7:0]  io_sum_8,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input  [7:0]  io_sum_9,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input  [7:0]  io_sum_10,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input  [7:0]  io_sum_11,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input  [7:0]  io_sum_12,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input  [7:0]  io_sum_13,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input  [7:0]  io_sum_14,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input  [7:0]  io_sum_15,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_carry_0,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_carry_1,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_carry_2,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_carry_3,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_carry_4,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_carry_5,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_carry_6,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_carry_7,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_carry_8,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_carry_9,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_carry_10,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_carry_11,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_carry_12,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_carry_13,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_carry_14,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_carry_15,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in1_sign_0,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in1_sign_1,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in1_sign_2,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in1_sign_3,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in1_sign_4,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in1_sign_5,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in1_sign_6,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in1_sign_7,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in1_sign_8,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in1_sign_9,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in1_sign_10,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in1_sign_11,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in1_sign_12,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in1_sign_13,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in1_sign_14,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in1_sign_15,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in2_sign_0,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in2_sign_1,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in2_sign_2,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in2_sign_3,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in2_sign_4,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in2_sign_5,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in2_sign_6,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in2_sign_7,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in2_sign_8,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in2_sign_9,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in2_sign_10,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in2_sign_11,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in2_sign_12,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in2_sign_13,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in2_sign_14,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_in2_sign_15,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_sub,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input  [1:0]  io_eew,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  input         io_signed,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [15:0] io_set_vxsat,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [7:0]  io_out_0,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [7:0]  io_out_1,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [7:0]  io_out_2,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [7:0]  io_out_3,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [7:0]  io_out_4,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [7:0]  io_out_5,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [7:0]  io_out_6,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [7:0]  io_out_7,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [7:0]  io_out_8,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [7:0]  io_out_9,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [7:0]  io_out_10,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [7:0]  io_out_11,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [7:0]  io_out_12,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [7:0]  io_out_13,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [7:0]  io_out_14,	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
  output [7:0]  io_out_15	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:138:14]
);

  wire              _unsigned_mask_WIRE_1_0 = io_sub ^ io_carry_1;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:152:74]
  wire              _unsigned_mask_WIRE_2_0 = io_sub ^ io_carry_3;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:152:74]
  wire              _unsigned_mask_WIRE_1_2 = io_sub ^ io_carry_5;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:152:74]
  wire              _unsigned_mask_WIRE_3_0 = io_sub ^ io_carry_7;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:152:74]
  wire              _unsigned_mask_WIRE_1_4 = io_sub ^ io_carry_9;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:152:74]
  wire              _unsigned_mask_WIRE_2_2 = io_sub ^ io_carry_11;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:152:74]
  wire              _unsigned_mask_WIRE_1_6 = io_sub ^ io_carry_13;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:152:74]
  wire              _unsigned_mask_WIRE_3_1 = io_sub ^ io_carry_15;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:152:74]
  wire [127:0]      _unsigned_clip_WIRE = io_sub ? 128'h0 : 128'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:154:{26,48}]
  wire [15:0]       vs2_sign = {io_in2_sign_15, io_in2_sign_14, io_in2_sign_13, io_in2_sign_12, io_in2_sign_11, io_in2_sign_10, io_in2_sign_9, io_in2_sign_8, io_in2_sign_7, io_in2_sign_6, io_in2_sign_5, io_in2_sign_4, io_in2_sign_3, io_in2_sign_2, io_in2_sign_1, io_in2_sign_0};	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:158:88]
  wire [15:0]       may_clip = {16{~io_sub}} ^ vs2_sign ^ {io_in1_sign_15, io_in1_sign_14, io_in1_sign_13, io_in1_sign_12, io_in1_sign_11, io_in1_sign_10, io_in1_sign_9, io_in1_sign_8, io_in1_sign_7, io_in1_sign_6, io_in1_sign_5, io_in1_sign_4, io_in1_sign_3, io_in1_sign_2, io_in1_sign_1, io_in1_sign_0};	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:158:88, :159:88, :161:25]
  wire [15:0]       _clip_T = vs2_sign ^ {io_sum_15[7], io_sum_14[7], io_sum_13[7], io_sum_12[7], io_sum_11[7], io_sum_10[7], io_sum_9[7], io_sum_8[7], io_sum_7[7], io_sum_6[7], io_sum_5[7], io_sum_4[7], io_sum_3[7], io_sum_2[7], io_sum_1[7], io_sum_0[7]};	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:157:{83,88}, :158:88, :162:32]
  wire [7:0]        vs2_sign_1 = {io_in2_sign_15, io_in2_sign_13, io_in2_sign_11, io_in2_sign_9, io_in2_sign_7, io_in2_sign_5, io_in2_sign_3, io_in2_sign_1};	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:158:88]
  wire [7:0]        may_clip_1 = {8{~io_sub}} ^ vs2_sign_1 ^ {io_in1_sign_15, io_in1_sign_13, io_in1_sign_11, io_in1_sign_9, io_in1_sign_7, io_in1_sign_5, io_in1_sign_3, io_in1_sign_1};	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:158:88, :159:88, :161:25]
  wire [7:0]        _clip_T_1 = vs2_sign_1 ^ {io_sum_15[7], io_sum_13[7], io_sum_11[7], io_sum_9[7], io_sum_7[7], io_sum_5[7], io_sum_3[7], io_sum_1[7]};	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:157:{83,88}, :158:88, :162:32]
  wire [3:0]        vs2_sign_2 = {io_in2_sign_15, io_in2_sign_11, io_in2_sign_7, io_in2_sign_3};	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:158:88]
  wire [3:0]        may_clip_2 = {4{~io_sub}} ^ vs2_sign_2 ^ {io_in1_sign_15, io_in1_sign_11, io_in1_sign_7, io_in1_sign_3};	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:158:88, :159:88, :161:25]
  wire [3:0]        _clip_T_2 = vs2_sign_2 ^ {io_sum_15[7], io_sum_11[7], io_sum_7[7], io_sum_3[7]};	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:157:{83,88}, :158:88, :162:32]
  wire [1:0]        vs2_sign_3 = {io_in2_sign_15, io_in2_sign_7};	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:158:88]
  wire [1:0]        may_clip_3 = {2{~io_sub}} ^ vs2_sign_3 ^ {io_in1_sign_15, io_in1_sign_7};	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:158:88, :159:88, :161:25]
  wire [1:0]        _clip_T_3 = vs2_sign_3 ^ {io_sum_15[7], io_sum_7[7]};	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:157:{83,88}, :158:88, :162:32]
  wire [3:0][127:0] _GEN = {{{io_in2_sign_15 ? 64'h8000000000000000 : 64'h7FFFFFFFFFFFFFFF, io_in2_sign_7 ? 64'h8000000000000000 : 64'h7FFFFFFFFFFFFFFF}}, {{io_in2_sign_15 ? 32'h80000000 : 32'h7FFFFFFF, io_in2_sign_11 ? 32'h80000000 : 32'h7FFFFFFF, io_in2_sign_7 ? 32'h80000000 : 32'h7FFFFFFF, io_in2_sign_3 ? 32'h80000000 : 32'h7FFFFFFF}}, {{io_in2_sign_15 ? 16'h8000 : 16'h7FFF, io_in2_sign_13 ? 16'h8000 : 16'h7FFF, io_in2_sign_11 ? 16'h8000 : 16'h7FFF, io_in2_sign_9 ? 16'h8000 : 16'h7FFF, io_in2_sign_7 ? 16'h8000 : 16'h7FFF, io_in2_sign_5 ? 16'h8000 : 16'h7FFF, io_in2_sign_3 ? 16'h8000 : 16'h7FFF, io_in2_sign_1 ? 16'h8000 : 16'h7FFF}}, {{io_in2_sign_15 ? 8'h80 : 8'h7F, io_in2_sign_14 ? 8'h80 : 8'h7F, io_in2_sign_13 ? 8'h80 : 8'h7F, io_in2_sign_12 ? 8'h80 : 8'h7F, io_in2_sign_11 ? 8'h80 : 8'h7F, io_in2_sign_10 ? 8'h80 : 8'h7F, io_in2_sign_9 ? 8'h80 : 8'h7F, io_in2_sign_8 ? 8'h80 : 8'h7F, io_in2_sign_7 ? 8'h80 : 8'h7F, io_in2_sign_6 ? 8'h80 : 8'h7F, io_in2_sign_5 ? 8'h80 : 8'h7F, io_in2_sign_4 ? 8'h80 : 8'h7F, io_in2_sign_3 ? 8'h80 : 8'h7F, io_in2_sign_2 ? 8'h80 : 8'h7F, io_in2_sign_1 ? 8'h80 : 8'h7F, io_in2_sign_0 ? 8'h80 : 8'h7F}}};	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:163:25, :164:22, :165:{62,91}, :169:59]
  wire [3:0][15:0]  _GEN_0 = {{{{8{_clip_T_3[1] & may_clip_3[1]}}, {8{_clip_T_3[0] & may_clip_3[0]}}}}, {{{4{_clip_T_2[3] & may_clip_2[3]}}, {4{_clip_T_2[2] & may_clip_2[2]}}, {4{_clip_T_2[1] & may_clip_2[1]}}, {4{_clip_T_2[0] & may_clip_2[0]}}}}, {{{2{_clip_T_1[7] & may_clip_1[7]}}, {2{_clip_T_1[6] & may_clip_1[6]}}, {2{_clip_T_1[5] & may_clip_1[5]}}, {2{_clip_T_1[4] & may_clip_1[4]}}, {2{_clip_T_1[3] & may_clip_1[3]}}, {2{_clip_T_1[2] & may_clip_1[2]}}, {2{_clip_T_1[1] & may_clip_1[1]}}, {2{_clip_T_1[0] & may_clip_1[0]}}}}, {{_clip_T[15] & may_clip[15], _clip_T[14] & may_clip[14], _clip_T[13] & may_clip[13], _clip_T[12] & may_clip[12], _clip_T[11] & may_clip[11], _clip_T[10] & may_clip[10], _clip_T[9] & may_clip[9], _clip_T[8] & may_clip[8], _clip_T[7] & may_clip[7], _clip_T[6] & may_clip[6], _clip_T[5] & may_clip[5], _clip_T[4] & may_clip[4], _clip_T[3] & may_clip[3], _clip_T[2] & may_clip[2], _clip_T[1] & may_clip[1], _clip_T[0] & may_clip[0]}}};	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:161:25, :162:{32,44}, :166:21, :171:17]
  wire [3:0][15:0]  _GEN_1 = {{{{8{_unsigned_mask_WIRE_3_1}}, {8{_unsigned_mask_WIRE_3_0}}}}, {{{4{_unsigned_mask_WIRE_3_1}}, {4{_unsigned_mask_WIRE_2_2}}, {4{_unsigned_mask_WIRE_3_0}}, {4{_unsigned_mask_WIRE_2_0}}}}, {{{2{_unsigned_mask_WIRE_3_1}}, {2{_unsigned_mask_WIRE_1_6}}, {2{_unsigned_mask_WIRE_2_2}}, {2{_unsigned_mask_WIRE_1_4}}, {2{_unsigned_mask_WIRE_3_0}}, {2{_unsigned_mask_WIRE_1_2}}, {2{_unsigned_mask_WIRE_2_0}}, {2{_unsigned_mask_WIRE_1_0}}}}, {{_unsigned_mask_WIRE_3_1, io_sub ^ io_carry_14, _unsigned_mask_WIRE_1_6, io_sub ^ io_carry_12, _unsigned_mask_WIRE_2_2, io_sub ^ io_carry_10, _unsigned_mask_WIRE_1_4, io_sub ^ io_carry_8, _unsigned_mask_WIRE_3_0, io_sub ^ io_carry_6, _unsigned_mask_WIRE_1_2, io_sub ^ io_carry_4, _unsigned_mask_WIRE_2_0, io_sub ^ io_carry_2, _unsigned_mask_WIRE_1_0, io_sub ^ io_carry_0}}};	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:152:{20,74,104}, :171:17]
  wire [15:0]       mask = io_signed ? _GEN_0[io_eew] : _GEN_1[io_eew];	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:171:17]
  assign io_set_vxsat = mask;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :171:17]
  assign io_out_0 = mask[0] ? (io_signed ? _GEN[io_eew][7:0] : _unsigned_clip_WIRE[7:0]) : io_sum_0;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :154:{26,72}, :169:59, :171:17, :172:17, :173:{56,61}]
  assign io_out_1 = mask[1] ? (io_signed ? _GEN[io_eew][15:8] : _unsigned_clip_WIRE[15:8]) : io_sum_1;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :154:{26,72}, :169:59, :171:17, :172:17, :173:{56,61}]
  assign io_out_2 = mask[2] ? (io_signed ? _GEN[io_eew][23:16] : _unsigned_clip_WIRE[23:16]) : io_sum_2;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :154:{26,72}, :169:59, :171:17, :172:17, :173:{56,61}]
  assign io_out_3 = mask[3] ? (io_signed ? _GEN[io_eew][31:24] : _unsigned_clip_WIRE[31:24]) : io_sum_3;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :154:{26,72}, :169:59, :171:17, :172:17, :173:{56,61}]
  assign io_out_4 = mask[4] ? (io_signed ? _GEN[io_eew][39:32] : _unsigned_clip_WIRE[39:32]) : io_sum_4;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :154:{26,72}, :169:59, :171:17, :172:17, :173:{56,61}]
  assign io_out_5 = mask[5] ? (io_signed ? _GEN[io_eew][47:40] : _unsigned_clip_WIRE[47:40]) : io_sum_5;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :154:{26,72}, :169:59, :171:17, :172:17, :173:{56,61}]
  assign io_out_6 = mask[6] ? (io_signed ? _GEN[io_eew][55:48] : _unsigned_clip_WIRE[55:48]) : io_sum_6;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :154:{26,72}, :169:59, :171:17, :172:17, :173:{56,61}]
  assign io_out_7 = mask[7] ? (io_signed ? _GEN[io_eew][63:56] : _unsigned_clip_WIRE[63:56]) : io_sum_7;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :154:{26,72}, :169:59, :171:17, :172:17, :173:{56,61}]
  assign io_out_8 = mask[8] ? (io_signed ? _GEN[io_eew][71:64] : _unsigned_clip_WIRE[71:64]) : io_sum_8;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :154:{26,72}, :169:59, :171:17, :172:17, :173:{56,61}]
  assign io_out_9 = mask[9] ? (io_signed ? _GEN[io_eew][79:72] : _unsigned_clip_WIRE[79:72]) : io_sum_9;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :154:{26,72}, :169:59, :171:17, :172:17, :173:{56,61}]
  assign io_out_10 = mask[10] ? (io_signed ? _GEN[io_eew][87:80] : _unsigned_clip_WIRE[87:80]) : io_sum_10;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :154:{26,72}, :169:59, :171:17, :172:17, :173:{56,61}]
  assign io_out_11 = mask[11] ? (io_signed ? _GEN[io_eew][95:88] : _unsigned_clip_WIRE[95:88]) : io_sum_11;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :154:{26,72}, :169:59, :171:17, :172:17, :173:{56,61}]
  assign io_out_12 = mask[12] ? (io_signed ? _GEN[io_eew][103:96] : _unsigned_clip_WIRE[103:96]) : io_sum_12;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :154:{26,72}, :169:59, :171:17, :172:17, :173:{56,61}]
  assign io_out_13 = mask[13] ? (io_signed ? _GEN[io_eew][111:104] : _unsigned_clip_WIRE[111:104]) : io_sum_13;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :154:{26,72}, :169:59, :171:17, :172:17, :173:{56,61}]
  assign io_out_14 = mask[14] ? (io_signed ? _GEN[io_eew][119:112] : _unsigned_clip_WIRE[119:112]) : io_sum_14;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :154:{26,72}, :169:59, :171:17, :172:17, :173:{56,61}]
  assign io_out_15 = mask[15] ? (io_signed ? _GEN[io_eew][127:120] : _unsigned_clip_WIRE[127:120]) : io_sum_15;	// @[generators/saturn/src/main/scala/exu/int/IntegerPipe.scala:136:7, :154:{26,72}, :169:59, :171:17, :172:17, :173:{56,61}]
endmodule

