// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module ShuttleICache(	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
  input         clock,	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
  input         reset,	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
  input         auto_master_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_master_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_master_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_master_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_master_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_master_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_master_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         io_req_valid,	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:36:14]
  input  [38:0] io_req_bits,	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:36:14]
  input         io_s1_kill,	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:36:14]
  input         io_s2_kill,	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:36:14]
  input  [31:0] io_s1_paddr,	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:36:14]
  input         io_invalidate,	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:36:14]
  output        io_resp_valid,	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:36:14]
  output [63:0] io_resp_bits	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:36:14]
);

  wire         data_arrays_0_dout_en;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:148:46]
  wire         data_arrays_0_MPORT_1_en;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:140:32]
  wire         data_arrays_0_MPORT_1_mask_7;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:94:97]
  wire         data_arrays_0_MPORT_1_mask_6;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:94:97]
  wire         data_arrays_0_MPORT_1_mask_5;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:94:97]
  wire         data_arrays_0_MPORT_1_mask_4;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:94:97]
  wire         data_arrays_0_MPORT_1_mask_3;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:94:97]
  wire         data_arrays_0_MPORT_1_mask_2;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:94:97]
  wire         data_arrays_0_MPORT_1_mask_1;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:94:97]
  wire         data_arrays_0_MPORT_1_mask_0;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:94:97]
  wire         tag_array_tag_rdata_en;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:90:83]
  wire [5:0]   _tag_rdata_WIRE;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:90:42]
  wire         _io_req_ready_T;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:72:19]
  wire         masterNodeOut_a_valid;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:65:35]
  wire [511:0] _data_arrays_0_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [159:0] _tag_array_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire         _repl_way_prng_io_out_0;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire         _repl_way_prng_io_out_1;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire         _repl_way_prng_io_out_2;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire         s0_ren = _io_req_ready_T & io_req_valid;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:72:19, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg          s1_valid;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:51:25]
  reg          s2_valid;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:55:25]
  reg          s2_hit;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:56:23]
  reg          invalidated;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:58:24]
  reg          refill_valid;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:59:29]
  wire         _refill_fire_T = auto_master_out_a_ready & masterNodeOut_a_valid;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:65:35, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire         s2_miss = s2_valid & ~s2_hit & ~io_s2_kill;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:55:25, :56:23, :63:{29,37,40}]
  reg          s2_request_refill_REG;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:65:45]
  assign masterNodeOut_a_valid = s2_miss & s2_request_refill_REG;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:63:37, :65:{35,45}]
  reg  [31:0]  refill_paddr;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:66:31]
  wire         refill_one_beat = auto_master_out_d_valid & auto_master_out_d_bits_opcode[0];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, generators/shuttle/src/main/scala/ifu/ICache.scala:70:39]
  assign _io_req_ready_T = ~refill_one_beat;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:70:39, :72:19]
  wire [26:0]  _r_beats1_decode_T = 27'hFFF << auto_master_out_d_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  wire [8:0]   r_beats1 = auto_master_out_d_bits_opcode[0] ? ~(_r_beats1_decode_T[11:3]) : 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, :221:14, :229:27, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
  reg  [8:0]   r_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  wire [8:0]   _r_counter1_T = r_counter - 9'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :230:28]
  wire         tag_array_MPORT_en = refill_one_beat & (r_counter == 9'h1 | r_beats1 == 9'h0) & auto_master_out_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27, :232:{25,33,43}, generators/shuttle/src/main/scala/ifu/ICache.scala:70:39, :76:37]
  wire [2:0]   repl_way = {_repl_way_prng_io_out_2, _repl_way_prng_io_out_1, _repl_way_prng_io_out_0};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:81:26, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire [7:0]   _GEN = {data_arrays_0_MPORT_1_mask_7, data_arrays_0_MPORT_1_mask_6, data_arrays_0_MPORT_1_mask_5, data_arrays_0_MPORT_1_mask_4, data_arrays_0_MPORT_1_mask_3, data_arrays_0_MPORT_1_mask_2, data_arrays_0_MPORT_1_mask_1, data_arrays_0_MPORT_1_mask_0};	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:94:97]
  assign _tag_rdata_WIRE = io_req_bits[11:6];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:90:42]
  assign tag_array_tag_rdata_en = ~tag_array_MPORT_en & s0_ren;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:76:37, :90:{70,83}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign data_arrays_0_MPORT_1_mask_0 = repl_way == 3'h0;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:81:26, :94:97]
  assign data_arrays_0_MPORT_1_mask_1 = repl_way == 3'h1;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:81:26, :94:97]
  assign data_arrays_0_MPORT_1_mask_2 = repl_way == 3'h2;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:81:26, :94:97]
  assign data_arrays_0_MPORT_1_mask_3 = repl_way == 3'h3;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:81:26, :94:97]
  assign data_arrays_0_MPORT_1_mask_4 = repl_way == 3'h4;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:81:26, :94:97]
  assign data_arrays_0_MPORT_1_mask_5 = repl_way == 3'h5;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:81:26, :94:97]
  assign data_arrays_0_MPORT_1_mask_6 = repl_way == 3'h6;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:81:26, :94:97]
  assign data_arrays_0_MPORT_1_mask_7 = &repl_way;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:81:26, :94:97]
  reg  [511:0] vb_array;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:97:25]
  wire [511:0] _s1_vb_T_1 = vb_array >> io_s1_paddr[11:6];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:97:25, :115:25, :212:21]
  wire         s1_tag_hit_0 = _s1_vb_T_1[0] & _tag_array_RW0_rdata[19:0] == io_s1_paddr[31:12];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:114:30, :115:25, :118:{26,33}]
  wire [511:0] _s1_vb_T_3 = vb_array >> {506'h1, io_s1_paddr[11:6]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:97:25, :115:25, :212:21]
  wire         s1_tag_hit_1 = _s1_vb_T_3[0] & _tag_array_RW0_rdata[39:20] == io_s1_paddr[31:12];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:114:30, :115:25, :118:{26,33}]
  wire [511:0] _s1_vb_T_5 = vb_array >> {506'h2, io_s1_paddr[11:6]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:97:25, :115:25, :212:21]
  wire         s1_tag_hit_2 = _s1_vb_T_5[0] & _tag_array_RW0_rdata[59:40] == io_s1_paddr[31:12];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:114:30, :115:25, :118:{26,33}]
  wire [511:0] _s1_vb_T_7 = vb_array >> {506'h3, io_s1_paddr[11:6]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:97:25, :115:25, :212:21]
  wire         s1_tag_hit_3 = _s1_vb_T_7[0] & _tag_array_RW0_rdata[79:60] == io_s1_paddr[31:12];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:114:30, :115:25, :118:{26,33}]
  wire [511:0] _s1_vb_T_9 = vb_array >> {506'h4, io_s1_paddr[11:6]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:97:25, :115:25, :212:21]
  wire         s1_tag_hit_4 = _s1_vb_T_9[0] & _tag_array_RW0_rdata[99:80] == io_s1_paddr[31:12];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:114:30, :115:25, :118:{26,33}]
  wire [511:0] _s1_vb_T_11 = vb_array >> {506'h5, io_s1_paddr[11:6]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:97:25, :115:25, :212:21]
  wire         s1_tag_hit_5 = _s1_vb_T_11[0] & _tag_array_RW0_rdata[119:100] == io_s1_paddr[31:12];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:114:30, :115:25, :118:{26,33}]
  wire [511:0] _s1_vb_T_13 = vb_array >> {506'h6, io_s1_paddr[11:6]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:97:25, :115:25, :212:21]
  wire         s1_tag_hit_6 = _s1_vb_T_13[0] & _tag_array_RW0_rdata[139:120] == io_s1_paddr[31:12];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:114:30, :115:25, :118:{26,33}]
  wire [511:0] _s1_vb_T_15 = vb_array >> {506'h7, io_s1_paddr[11:6]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:97:25, :115:25, :212:21]
  wire         s1_tag_hit_7 = _s1_vb_T_15[0] & _tag_array_RW0_rdata[159:140] == io_s1_paddr[31:12];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:114:30, :115:25, :118:{26,33}]
  `ifndef SYNTHESIS	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:121:9]
    always @(posedge clock) begin	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:121:9]
      if (~reset & ~(~s1_valid | {1'h0, {1'h0, {1'h0, s1_tag_hit_0} + {1'h0, s1_tag_hit_1}} + {1'h0, {1'h0, s1_tag_hit_2} + {1'h0, s1_tag_hit_3}}} + {1'h0, {1'h0, {1'h0, s1_tag_hit_4} + {1'h0, s1_tag_hit_5}} + {1'h0, {1'h0, s1_tag_hit_6} + {1'h0, s1_tag_hit_7}}} < 4'h2)) begin	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :51:25, :118:26, :121:{9,10,20,31,44}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:121:9]
          $error("Assertion failed\n    at ICache.scala:121 assert(!s1_valid || PopCount(s1_tag_hit) <= 1.U)\n");	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:121:9]
        if (`STOP_COND_)	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:121:9]
          $fatal;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:121:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  assign data_arrays_0_MPORT_1_en = refill_one_beat & ~invalidated;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:58:24, :70:39, :140:{32,35}]
  assign data_arrays_0_dout_en = ~data_arrays_0_MPORT_1_en & s0_ren;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:140:32, :148:{41,46}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg          s2_tag_hit_0;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:155:29]
  reg          s2_tag_hit_1;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:155:29]
  reg          s2_tag_hit_2;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:155:29]
  reg          s2_tag_hit_3;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:155:29]
  reg          s2_tag_hit_4;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:155:29]
  reg          s2_tag_hit_5;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:155:29]
  reg          s2_tag_hit_6;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:155:29]
  reg          s2_tag_hit_7;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:155:29]
  reg  [63:0]  s2_dout_0;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:157:26]
  reg  [63:0]  s2_dout_1;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:157:26]
  reg  [63:0]  s2_dout_2;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:157:26]
  reg  [63:0]  s2_dout_3;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:157:26]
  reg  [63:0]  s2_dout_4;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:157:26]
  reg  [63:0]  s2_dout_5;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:157:26]
  reg  [63:0]  s2_dout_6;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:157:26]
  reg  [63:0]  s2_dout_7;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:157:26]
  wire [511:0] _vb_array_T_3 = 512'h1 << {503'h0, _repl_way_prng_io_out_2, _repl_way_prng_io_out_1, _repl_way_prng_io_out_0, refill_paddr[11:6]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:66:31, :100:32, :212:21, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire         _s1_can_request_refill_T = s2_miss | refill_valid;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:59:29, :63:37, :64:41]
  always @(posedge clock) begin	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
    if (reset) begin	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
      s1_valid <= 1'h0;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :51:25]
      s2_valid <= 1'h0;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :55:25]
      refill_valid <= 1'h0;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :59:29]
      r_counter <= 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      vb_array <= 512'h0;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:97:25]
    end
    else begin	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
      s1_valid <= s0_ren;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:51:25, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      s2_valid <= s1_valid & ~io_s1_kill;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:51:25, :55:{25,35,38}]
      refill_valid <= ~tag_array_MPORT_en & (_refill_fire_T | refill_valid);	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:59:29, :76:37, :208:{22,37}, :209:{22,37}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      if (auto_master_out_d_valid) begin	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
        if (r_counter == 9'h0)	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25]
          r_counter <= r_beats1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27]
        else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25]
          r_counter <= _r_counter1_T;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :230:28]
      end
      if (io_invalidate)	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:36:14]
        vb_array <= 512'h0;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:97:25]
      else if (refill_one_beat) begin	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:70:39]
        if (tag_array_MPORT_en & ~invalidated)	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:58:24, :76:37, :100:{72,75}]
          vb_array <= vb_array | _vb_array_T_3;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:97:25, :100:32]
        else	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:100:72]
          vb_array <= ~(~vb_array | _vb_array_T_3);	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:97:25, :100:32]
      end
    end
    s2_hit <= s1_tag_hit_0 | s1_tag_hit_1 | s1_tag_hit_2 | s1_tag_hit_3 | s1_tag_hit_4 | s1_tag_hit_5 | s1_tag_hit_6 | s1_tag_hit_7;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:54:35, :56:23, :118:26]
    invalidated <= refill_valid & (io_invalidate | invalidated);	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:58:24, :59:29, :103:21, :105:17, :207:{24,38}]
    s2_request_refill_REG <= ~_s1_can_request_refill_T;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:64:{31,41}, :65:45]
    if (s1_valid & ~_s1_can_request_refill_T)	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:51:25, :64:{31,41}, :66:54]
      refill_paddr <= io_s1_paddr;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:66:31]
    if (s1_valid) begin	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:51:25]
      s2_tag_hit_0 <= s1_tag_hit_0;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:118:26, :155:29]
      s2_tag_hit_1 <= s1_tag_hit_1;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:118:26, :155:29]
      s2_tag_hit_2 <= s1_tag_hit_2;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:118:26, :155:29]
      s2_tag_hit_3 <= s1_tag_hit_3;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:118:26, :155:29]
      s2_tag_hit_4 <= s1_tag_hit_4;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:118:26, :155:29]
      s2_tag_hit_5 <= s1_tag_hit_5;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:118:26, :155:29]
      s2_tag_hit_6 <= s1_tag_hit_6;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:118:26, :155:29]
      s2_tag_hit_7 <= s1_tag_hit_7;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:118:26, :155:29]
      s2_dout_0 <= _data_arrays_0_RW0_rdata[63:0];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:157:26]
      s2_dout_1 <= _data_arrays_0_RW0_rdata[127:64];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:157:26]
      s2_dout_2 <= _data_arrays_0_RW0_rdata[191:128];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:157:26]
      s2_dout_3 <= _data_arrays_0_RW0_rdata[255:192];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:157:26]
      s2_dout_4 <= _data_arrays_0_RW0_rdata[319:256];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:157:26]
      s2_dout_5 <= _data_arrays_0_RW0_rdata[383:320];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:157:26]
      s2_dout_6 <= _data_arrays_0_RW0_rdata[447:384];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:157:26]
      s2_dout_7 <= _data_arrays_0_RW0_rdata[511:448];	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:157:26]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:36];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
    initial begin	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
        `INIT_RANDOM_PROLOG_	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
        for (logic [5:0] i = 6'h0; i < 6'h25; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
        end	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
        s1_valid = _RANDOM[6'h0][0];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :51:25]
        s2_valid = _RANDOM[6'h1][8];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :55:25]
        s2_hit = _RANDOM[6'h1][9];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :55:25, :56:23]
        invalidated = _RANDOM[6'h1][10];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :55:25, :58:24]
        refill_valid = _RANDOM[6'h1][11];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :55:25, :59:29]
        s2_request_refill_REG = _RANDOM[6'h1][14];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :55:25, :65:45]
        refill_paddr = {_RANDOM[6'h1][31:15], _RANDOM[6'h2][14:0]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :55:25, :66:31]
        r_counter = _RANDOM[6'h3][30:22];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
        vb_array = {_RANDOM[6'h3][31], _RANDOM[6'h4], _RANDOM[6'h5], _RANDOM[6'h6], _RANDOM[6'h7], _RANDOM[6'h8], _RANDOM[6'h9], _RANDOM[6'hA], _RANDOM[6'hB], _RANDOM[6'hC], _RANDOM[6'hD], _RANDOM[6'hE], _RANDOM[6'hF], _RANDOM[6'h10], _RANDOM[6'h11], _RANDOM[6'h12], _RANDOM[6'h13][30:0]};	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :97:25]
        s2_tag_hit_0 = _RANDOM[6'h13][31];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :97:25, :155:29]
        s2_tag_hit_1 = _RANDOM[6'h14][0];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :155:29]
        s2_tag_hit_2 = _RANDOM[6'h14][1];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :155:29]
        s2_tag_hit_3 = _RANDOM[6'h14][2];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :155:29]
        s2_tag_hit_4 = _RANDOM[6'h14][3];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :155:29]
        s2_tag_hit_5 = _RANDOM[6'h14][4];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :155:29]
        s2_tag_hit_6 = _RANDOM[6'h14][5];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :155:29]
        s2_tag_hit_7 = _RANDOM[6'h14][6];	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :155:29]
        s2_dout_0 = {_RANDOM[6'h14][31:7], _RANDOM[6'h15], _RANDOM[6'h16][6:0]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :155:29, :157:26]
        s2_dout_1 = {_RANDOM[6'h16][31:7], _RANDOM[6'h17], _RANDOM[6'h18][6:0]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :157:26]
        s2_dout_2 = {_RANDOM[6'h18][31:7], _RANDOM[6'h19], _RANDOM[6'h1A][6:0]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :157:26]
        s2_dout_3 = {_RANDOM[6'h1A][31:7], _RANDOM[6'h1B], _RANDOM[6'h1C][6:0]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :157:26]
        s2_dout_4 = {_RANDOM[6'h1C][31:7], _RANDOM[6'h1D], _RANDOM[6'h1E][6:0]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :157:26]
        s2_dout_5 = {_RANDOM[6'h1E][31:7], _RANDOM[6'h1F], _RANDOM[6'h20][6:0]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :157:26]
        s2_dout_6 = {_RANDOM[6'h20][31:7], _RANDOM[6'h21], _RANDOM[6'h22][6:0]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :157:26]
        s2_dout_7 = {_RANDOM[6'h22][31:7], _RANDOM[6'h23], _RANDOM[6'h24][6:0]};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :157:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MaxPeriodFibonacciLFSR repl_way_prng (	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
    .clock        (clock),
    .reset        (reset),
    .io_increment (_refill_fire_T),	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
    .io_out_0     (_repl_way_prng_io_out_0),
    .io_out_1     (_repl_way_prng_io_out_1),
    .io_out_2     (_repl_way_prng_io_out_2),
    .io_out_3     (/* unused */),
    .io_out_4     (/* unused */),
    .io_out_5     (/* unused */),
    .io_out_6     (/* unused */),
    .io_out_7     (/* unused */),
    .io_out_8     (/* unused */),
    .io_out_9     (/* unused */),
    .io_out_10    (/* unused */),
    .io_out_11    (/* unused */),
    .io_out_12    (/* unused */),
    .io_out_13    (/* unused */),
    .io_out_14    (/* unused */),
    .io_out_15    (/* unused */)
  );
  tag_array tag_array (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (tag_array_MPORT_en ? refill_paddr[11:6] : _tag_rdata_WIRE),	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:66:31, :76:37, :90:42, :212:21]
    .RW0_en    (tag_array_tag_rdata_en | tag_array_MPORT_en),	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:76:37, :90:83]
    .RW0_clk   (clock),
    .RW0_wmode (tag_array_MPORT_en),	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:76:37]
    .RW0_wdata ({8{refill_paddr[31:12]}}),	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:66:31, :68:33]
    .RW0_rdata (_tag_array_RW0_rdata),
    .RW0_wmask (_GEN)	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  );
  data_arrays_0 data_arrays_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (refill_one_beat ? {refill_paddr[11:6], 3'h0} | r_beats1 & ~_r_counter1_T : io_req_bits[11:3]),	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :230:28, :234:{25,27}, generators/shuttle/src/main/scala/ifu/ICache.scala:66:31, :70:39, :94:97, :138:31, :141:{22,52,79}, :212:21]
    .RW0_en    (data_arrays_0_dout_en | data_arrays_0_MPORT_1_en),	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/shuttle/src/main/scala/ifu/ICache.scala:140:32, :148:46]
    .RW0_clk   (clock),
    .RW0_wmode (data_arrays_0_MPORT_1_en),	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:140:32]
    .RW0_wdata ({8{auto_master_out_d_bits_data}}),	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_rdata (_data_arrays_0_RW0_rdata),
    .RW0_wmask (_GEN)	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  );
  assign auto_master_out_a_valid = masterNodeOut_a_valid;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :65:35]
  assign auto_master_out_a_bits_address = {refill_paddr[31:6], 6'h0};	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :66:31, :172:{47,64}]
  assign io_resp_valid = s2_valid & s2_hit;	// @[generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :55:25, :56:23, :167:29]
  assign io_resp_bits = (s2_tag_hit_0 ? s2_dout_0 : 64'h0) | (s2_tag_hit_1 ? s2_dout_1 : 64'h0) | (s2_tag_hit_2 ? s2_dout_2 : 64'h0) | (s2_tag_hit_3 ? s2_dout_3 : 64'h0) | (s2_tag_hit_4 ? s2_dout_4 : 64'h0) | (s2_tag_hit_5 ? s2_dout_5 : 64'h0) | (s2_tag_hit_6 ? s2_dout_6 : 64'h0) | (s2_tag_hit_7 ? s2_dout_7 : 64'h0);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:469:15, generators/shuttle/src/main/scala/ifu/ICache.scala:30:7, :155:29, :157:26, src/main/scala/chisel3/util/Mux.scala:30:73]
endmodule

