// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module CLINT(	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
  input         clock,	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
  input         reset,	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
  output        auto_int_out_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_int_out_1,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [12:0] auto_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [25:0] auto_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [7:0]  auto_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [12:0] auto_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         io_rtcTick	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:69:16]
);

  wire             out_woready_9;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             out_woready_17;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  reg  [63:0]      time_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:73:23]
  reg  [63:0]      pad;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:77:41]
  reg              ipi_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:78:41]
  wire             out_front_bits_read = auto_in_a_bits_opcode == 3'h4;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36]
  wire             _out_out_bits_data_WIRE_1 = auto_in_a_bits_address[13:3] == 11'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:192:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:75:19, :87:24]
  wire             valids_1_0 = out_woready_9 & auto_in_a_bits_mask[0];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             valids_1_1 = out_woready_9 & auto_in_a_bits_mask[1];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             valids_1_2 = out_woready_9 & auto_in_a_bits_mask[2];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             valids_1_3 = out_woready_9 & auto_in_a_bits_mask[3];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             valids_1_4 = out_woready_9 & auto_in_a_bits_mask[4];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             valids_1_5 = out_woready_9 & auto_in_a_bits_mask[5];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             valids_1_6 = out_woready_9 & auto_in_a_bits_mask[6];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             valids_1_7 = out_woready_9 & auto_in_a_bits_mask[7];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             valids_0 = out_woready_17 & auto_in_a_bits_mask[0];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             valids_1 = out_woready_17 & auto_in_a_bits_mask[1];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             valids_2 = out_woready_17 & auto_in_a_bits_mask[2];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             valids_3 = out_woready_17 & auto_in_a_bits_mask[3];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             valids_4 = out_woready_17 & auto_in_a_bits_mask[4];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             valids_5 = out_woready_17 & auto_in_a_bits_mask[5];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             valids_6 = out_woready_17 & auto_in_a_bits_mask[6];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             valids_7 = out_woready_17 & auto_in_a_bits_mask[7];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire             _out_wofireMux_T_2 = auto_in_a_valid & auto_in_d_ready & ~out_front_bits_read;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36, :87:24]
  assign out_woready_17 = _out_wofireMux_T_2 & auto_in_a_bits_address[15:14] == 2'h1 & _out_out_bits_data_WIRE_1;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign out_woready_9 = _out_wofireMux_T_2 & auto_in_a_bits_address[15:14] == 2'h2 & (&(auto_in_a_bits_address[13:3]));	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:192:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:75:19, :87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  wire [3:0]       _GEN = {{1'h1}, {&(auto_in_a_bits_address[13:3])}, {_out_out_bits_data_WIRE_1}, {_out_out_bits_data_WIRE_1}};	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:74:38, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:192:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:75:19, :87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:10]
  wire [3:0][63:0] _GEN_0 = {{64'h0}, {time_0}, {pad}, {{63'h0, ipi_0}}};	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:73:23, :77:41, :78:41, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:{10,48}]
  wire [2:0]       nodeIn_d_bits_opcode = {2'h0, out_front_bits_read};	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36, :105:19, src/main/scala/chisel3/util/OneHot.scala:58:35]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
    if (reset) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
      time_0 <= 64'h0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:73:23]
      ipi_0 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:78:41]
    end
    else begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
      if (valids_1_0 | valids_1_1 | valids_1_2 | valids_1_3 | valids_1_4 | valids_1_5 | valids_1_6 | valids_1_7)	// @[generators/rocket-chip/src/main/scala/regmapper/RegField.scala:154:27, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
        time_0 <= {valids_1_7 ? auto_in_a_bits_data[63:56] : time_0[63:56], valids_1_6 ? auto_in_a_bits_data[55:48] : time_0[55:48], valids_1_5 ? auto_in_a_bits_data[47:40] : time_0[47:40], valids_1_4 ? auto_in_a_bits_data[39:32] : time_0[39:32], valids_1_3 ? auto_in_a_bits_data[31:24] : time_0[31:24], valids_1_2 ? auto_in_a_bits_data[23:16] : time_0[23:16], valids_1_1 ? auto_in_a_bits_data[15:8] : time_0[15:8], valids_1_0 ? auto_in_a_bits_data[7:0] : time_0[7:0]};	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:73:23, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:151:57, :152:31, :154:52, :158:{20,33}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      else if (io_rtcTick)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:69:16]
        time_0 <= time_0 + 64'h1;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:73:23, :74:38]
      if (_out_wofireMux_T_2 & auto_in_a_bits_address[15:14] == 2'h0 & _out_out_bits_data_WIRE_1 & auto_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
        ipi_0 <= auto_in_a_bits_data[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:78:41, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    end
    if (valids_0 | valids_1 | valids_2 | valids_3 | valids_4 | valids_5 | valids_6 | valids_7)	// @[generators/rocket-chip/src/main/scala/regmapper/RegField.scala:154:27, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      pad <= {valids_7 ? auto_in_a_bits_data[63:56] : pad[63:56], valids_6 ? auto_in_a_bits_data[55:48] : pad[55:48], valids_5 ? auto_in_a_bits_data[47:40] : pad[47:40], valids_4 ? auto_in_a_bits_data[39:32] : pad[39:32], valids_3 ? auto_in_a_bits_data[31:24] : pad[31:24], valids_2 ? auto_in_a_bits_data[23:16] : pad[23:16], valids_1 ? auto_in_a_bits_data[15:8] : pad[15:8], valids_0 ? auto_in_a_bits_data[7:0] : pad[7:0]};	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:77:41, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:151:57, :152:31, :154:52, :158:{20,33}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:4];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
    initial begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
        end	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
        time_0 = {_RANDOM[3'h0], _RANDOM[3'h1]};	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9, :73:23]
        pad = {_RANDOM[3'h2], _RANDOM[3'h3]};	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9, :77:41]
        ipi_0 = _RANDOM[3'h4][0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9, :78:41]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLMonitor_49 monitor (	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (auto_in_d_ready),
    .io_in_a_valid        (auto_in_a_valid),
    .io_in_a_bits_opcode  (auto_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_a_bits_param),
    .io_in_a_bits_size    (auto_in_a_bits_size),
    .io_in_a_bits_source  (auto_in_a_bits_source),
    .io_in_a_bits_address (auto_in_a_bits_address),
    .io_in_a_bits_mask    (auto_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_a_bits_corrupt),
    .io_in_d_ready        (auto_in_d_ready),
    .io_in_d_valid        (auto_in_a_valid),
    .io_in_d_bits_opcode  (nodeIn_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:105:19]
    .io_in_d_bits_size    (auto_in_a_bits_size),
    .io_in_d_bits_source  (auto_in_a_bits_source)
  );
  assign auto_int_out_0 = ipi_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9, :78:41]
  assign auto_int_out_1 = time_0 >= pad;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9, :73:23, :77:41, :83:43]
  assign auto_in_a_ready = auto_in_d_ready;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
  assign auto_in_d_valid = auto_in_a_valid;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
  assign auto_in_d_bits_opcode = nodeIn_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:105:19]
  assign auto_in_d_bits_size = auto_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
  assign auto_in_d_bits_source = auto_in_a_bits_source;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9]
  assign auto_in_d_bits_data = _GEN[auto_in_a_bits_address[15:14]] ? _GEN_0[auto_in_a_bits_address[15:14]] : 64'h0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/CLINT.scala:65:9, :73:23, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:10]
endmodule

