// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module TLPLIC(	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
  input         clock,	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
  input         reset,	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
  input         auto_int_in_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_int_out_1_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_int_out_0_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [12:0] auto_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [27:0] auto_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [7:0]  auto_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [12:0] auto_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_in_d_bits_data	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  wire        out_woready_6;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_woready_9;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _out_rofireMux_T_1;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_backSel_10;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_backSel_8;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        completer_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:301:35]
  wire        completerDev;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/package.scala:163:13]
  wire        completer_1;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:301:35]
  wire        _out_back_front_q_io_enq_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _out_back_front_q_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _out_back_front_q_io_deq_bits_read;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [22:0] _out_back_front_q_io_deq_bits_index;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [63:0] _out_back_front_q_io_deq_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [7:0]  _out_back_front_q_io_deq_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [12:0] _out_back_front_q_io_deq_bits_extra_tlrr_extra_source;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [1:0]  _out_back_front_q_io_deq_bits_extra_tlrr_extra_size;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _fanin_1_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:189:27]
  wire        _fanin_1_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:189:27]
  wire        _fanin_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:189:27]
  wire        _fanin_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:189:27]
  wire        _gateways_gateway_io_plic_valid;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:160:27]
  reg         priority_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:167:31]
  reg         threshold_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:170:31]
  reg         threshold_1;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:170:31]
  reg         pending_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:172:26]
  reg         enables_0_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:178:26]
  reg         enables_1_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:178:26]
  reg         maxDevs_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:185:22]
  reg         maxDevs_1;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:185:22]
  reg         intnodeOut_0_REG;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:193:45]
  reg         intnodeOut_0_REG_1;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:193:45]
  wire [1:0]  _GEN = {1'h0, completerDev};	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/package.scala:163:13, src/main/scala/chisel3/util/OneHot.scala:65:12]
  wire        _out_T_11 = {_out_back_front_q_io_deq_bits_index[22:19], _out_back_front_q_io_deq_bits_index[17:11], _out_back_front_q_io_deq_bits_index[8:5], _out_back_front_q_io_deq_bits_index[3:0]} == 19'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [31:0] _out_womask_T_9 = {{8{_out_back_front_q_io_deq_bits_mask[7]}}, {8{_out_back_front_q_io_deq_bits_mask[6]}}, {8{_out_back_front_q_io_deq_bits_mask[5]}}, {8{_out_back_front_q_io_deq_bits_mask[4]}}};	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        claimer_1 = _out_rofireMux_T_1 & out_backSel_10 & _out_T_11 & (|_out_womask_T_9);	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [1:0]  _out_completer_1_T = {enables_1_0, 1'h0} >> _GEN;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :178:26, :183:52, :301:51, src/main/scala/chisel3/util/OneHot.scala:65:12]
  assign completer_1 = out_woready_6 & (&_out_womask_T_9) & _out_completer_1_T[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:301:{35,51}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        claimer_0 = _out_rofireMux_T_1 & out_backSel_8 & _out_T_11 & (|_out_womask_T_9);	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign completerDev = _out_back_front_q_io_deq_bits_data[32];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/package.scala:163:13]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:251:11]
    wire [1:0] _GEN_0 = {claimer_1, claimer_0};	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:251:21, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    wire [1:0] _GEN_1 = {completer_1, completer_0};	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:268:23, :301:35]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:251:11]
      if (~reset & (|(_GEN_0 & _GEN_0 - 2'h1))) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:251:{11,21,28,46,54}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:251:11]
          $error("Assertion failed\n    at Plic.scala:251 assert((claimer.asUInt & (claimer.asUInt - 1.U)) === 0.U) // One-Hot\n");	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:251:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:251:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:251:11]
      end
      if (~reset & (|(_GEN_1 & _GEN_1 - 2'h1))) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:251:11, :268:{11,23,30,50,58}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:268:11]
          $error("Assertion failed\n    at Plic.scala:268 assert((completer.asUInt & (completer.asUInt - 1.U)) === 0.U) // One-Hot\n");	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:268:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:268:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:268:11]
      end
      if (~reset & completerDev != _out_back_front_q_io_deq_bits_data[32]) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:298:{19,33}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/package.scala:163:13]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:298:19]
          $error("Assertion failed: completerDev should be consistent for all harts\n    at Plic.scala:298 assert(completerDev === data.extract(log2Ceil(nDevices+1)-1, 0),\n");	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:298:19]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:298:19]
          $fatal;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:298:19]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [1:0]  _out_completer_0_T = {enables_0_0, 1'h0} >> _GEN;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :178:26, :183:52, :301:51, src/main/scala/chisel3/util/OneHot.scala:65:12]
  assign completer_0 = out_woready_9 & (&_out_womask_T_9) & _out_completer_0_T[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:301:{35,51}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [3:0]  out_oindex = {_out_back_front_q_io_deq_bits_index[18], _out_back_front_q_io_deq_bits_index[10:9], _out_back_front_q_io_deq_bits_index[4]};	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [3:0]  _GEN_2 = {_out_back_front_q_io_deq_bits_index[18], _out_back_front_q_io_deq_bits_index[10:9], _out_back_front_q_io_deq_bits_index[4]};	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign out_backSel_8 = _GEN_2 == 4'h8;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:54:22, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign out_backSel_10 = _GEN_2 == 4'hA;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:54:22, src/main/scala/chisel3/util/OneHot.scala:58:35]
  wire        _out_wofireMux_T = _out_back_front_q_io_deq_valid & auto_in_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign _out_rofireMux_T_1 = _out_wofireMux_T & _out_back_front_q_io_deq_bits_read;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _out_wofireMux_T_2 = _out_wofireMux_T & ~_out_back_front_q_io_deq_bits_read;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign out_woready_9 = _out_wofireMux_T_2 & out_backSel_8 & _out_T_11;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign out_woready_6 = _out_wofireMux_T_2 & out_backSel_10 & _out_T_11;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _out_out_bits_data_T_6 = out_oindex == 4'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:54:22]
  wire [2:0]  nodeIn_d_bits_opcode = {2'h0, _out_back_front_q_io_deq_bits_read};	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, :105:19]
  wire        claimedDevs_1 = claimer_0 & maxDevs_0 | claimer_1 & maxDevs_1;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:185:22, :252:{49,92}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
    if (_out_wofireMux_T_2 & _GEN_2 == 4'h0 & _out_T_11 & _out_back_front_q_io_deq_bits_mask[4])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:54:22, src/main/scala/chisel3/util/OneHot.scala:58:35]
      priority_0 <= _out_back_front_q_io_deq_bits_data[32];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:167:31, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (out_woready_9 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      threshold_0 <= _out_back_front_q_io_deq_bits_data[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:170:31, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (out_woready_6 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      threshold_1 <= _out_back_front_q_io_deq_bits_data[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:170:31, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (_out_wofireMux_T_2 & _GEN_2 == 4'h4 & _out_T_11 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:54:22, src/main/scala/chisel3/util/OneHot.scala:58:35]
      enables_0_0 <= _out_back_front_q_io_deq_bits_data[1];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:178:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (_out_wofireMux_T_2 & _GEN_2 == 4'h5 & _out_T_11 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:54:22, src/main/scala/chisel3/util/OneHot.scala:58:35]
      enables_1_0 <= _out_back_front_q_io_deq_bits_data[1];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:178:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    maxDevs_0 <= _fanin_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:185:22, :189:27]
    maxDevs_1 <= _fanin_1_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:185:22, :189:27]
    intnodeOut_0_REG <= _fanin_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:189:27, :193:45]
    intnodeOut_0_REG_1 <= _fanin_1_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:189:27, :193:45]
    if (reset)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
      pending_0 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :172:26]
    else if (claimedDevs_1 | _gateways_gateway_io_plic_valid)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:160:27, :252:92, :257:15]
      pending_0 <= ~claimedDevs_1;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:172:26, :252:92, :257:34]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
    initial begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
        priority_0 = _RANDOM[/*Zero width*/ 1'b0][0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :167:31]
        threshold_0 = _RANDOM[/*Zero width*/ 1'b0][1];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :167:31, :170:31]
        threshold_1 = _RANDOM[/*Zero width*/ 1'b0][2];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :167:31, :170:31]
        pending_0 = _RANDOM[/*Zero width*/ 1'b0][3];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :167:31, :172:26]
        enables_0_0 = _RANDOM[/*Zero width*/ 1'b0][4];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :167:31, :178:26]
        enables_1_0 = _RANDOM[/*Zero width*/ 1'b0][5];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :167:31, :178:26]
        maxDevs_0 = _RANDOM[/*Zero width*/ 1'b0][6];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :167:31, :185:22]
        maxDevs_1 = _RANDOM[/*Zero width*/ 1'b0][7];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :167:31, :185:22]
        intnodeOut_0_REG = _RANDOM[/*Zero width*/ 1'b0][8];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :167:31, :193:45]
        intnodeOut_0_REG_1 = _RANDOM[/*Zero width*/ 1'b0][9];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :167:31, :193:45]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLMonitor_50 monitor (	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (_out_back_front_q_io_enq_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .io_in_a_valid        (auto_in_a_valid),
    .io_in_a_bits_opcode  (auto_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_a_bits_param),
    .io_in_a_bits_size    (auto_in_a_bits_size),
    .io_in_a_bits_source  (auto_in_a_bits_source),
    .io_in_a_bits_address (auto_in_a_bits_address),
    .io_in_a_bits_mask    (auto_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_a_bits_corrupt),
    .io_in_d_ready        (auto_in_d_ready),
    .io_in_d_valid        (_out_back_front_q_io_deq_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .io_in_d_bits_opcode  (nodeIn_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:105:19]
    .io_in_d_bits_size    (_out_back_front_q_io_deq_bits_extra_tlrr_extra_size),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .io_in_d_bits_source  (_out_back_front_q_io_deq_bits_extra_tlrr_extra_source)	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  );
  LevelGateway gateways_gateway (	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:160:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_0),
    .io_plic_valid    (_gateways_gateway_io_plic_valid),
    .io_plic_ready    (~pending_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:172:26, :256:18]
    .io_plic_complete ((completer_0 | completer_1) & completerDev)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:270:{28,48}, :301:35, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/package.scala:163:13]
  );
  PLICFanIn fanin (	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:189:27]
    .io_prio_0 (priority_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:167:31]
    .io_ip     (enables_0_0 & pending_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:172:26, :178:26, :191:40]
    .io_dev    (_fanin_io_dev),
    .io_max    (_fanin_io_max)
  );
  PLICFanIn fanin_1 (	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:189:27]
    .io_prio_0 (priority_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:167:31]
    .io_ip     (enables_1_0 & pending_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:172:26, :178:26, :191:40]
    .io_dev    (_fanin_1_io_dev),
    .io_max    (_fanin_1_io_max)
  );
  Queue1_RegMapperInput_i23_m8 out_back_front_q (	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .clock                               (clock),
    .reset                               (reset),
    .io_enq_ready                        (_out_back_front_q_io_enq_ready),
    .io_enq_valid                        (auto_in_a_valid),
    .io_enq_bits_read                    (auto_in_a_bits_opcode == 3'h4),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36]
    .io_enq_bits_index                   (auto_in_a_bits_address[25:3]),	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:192:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:75:19]
    .io_enq_bits_data                    (auto_in_a_bits_data),
    .io_enq_bits_mask                    (auto_in_a_bits_mask),
    .io_enq_bits_extra_tlrr_extra_source (auto_in_a_bits_source),
    .io_enq_bits_extra_tlrr_extra_size   (auto_in_a_bits_size),
    .io_deq_ready                        (auto_in_d_ready),
    .io_deq_valid                        (_out_back_front_q_io_deq_valid),
    .io_deq_bits_read                    (_out_back_front_q_io_deq_bits_read),
    .io_deq_bits_index                   (_out_back_front_q_io_deq_bits_index),
    .io_deq_bits_data                    (_out_back_front_q_io_deq_bits_data),
    .io_deq_bits_mask                    (_out_back_front_q_io_deq_bits_mask),
    .io_deq_bits_extra_tlrr_extra_source (_out_back_front_q_io_deq_bits_extra_tlrr_extra_source),
    .io_deq_bits_extra_tlrr_extra_size   (_out_back_front_q_io_deq_bits_extra_tlrr_extra_size)
  );
  assign auto_int_out_1_0 = intnodeOut_0_REG_1 > threshold_1;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :170:31, :193:{45,60}]
  assign auto_int_out_0_0 = intnodeOut_0_REG > threshold_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :170:31, :193:{45,60}]
  assign auto_in_a_ready = _out_back_front_q_io_enq_ready;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign auto_in_d_valid = _out_back_front_q_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign auto_in_d_bits_opcode = nodeIn_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:105:19]
  assign auto_in_d_bits_size = _out_back_front_q_io_deq_bits_extra_tlrr_extra_size;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign auto_in_d_bits_source = _out_back_front_q_io_deq_bits_extra_tlrr_extra_source;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign auto_in_d_bits_data = ~(_out_out_bits_data_T_6 | out_oindex == 4'h2 | out_oindex == 4'h4 | out_oindex == 4'h5 | out_oindex == 4'h8 | out_oindex == 4'hA) | _out_T_11 ? (_out_out_bits_data_T_6 ? {31'h0, priority_0, 32'h0} : out_oindex == 4'h2 ? {62'h0, pending_0, 1'h0} : out_oindex == 4'h4 ? {62'h0, enables_0_0, 1'h0} : out_oindex == 4'h5 ? {62'h0, enables_1_0, 1'h0} : out_oindex == 4'h8 ? {31'h0, maxDevs_0, 31'h0, threshold_0} : out_oindex == 4'hA ? {31'h0, maxDevs_1, 31'h0, threshold_1} : 64'h0) : 64'h0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :167:31, :170:31, :172:26, :178:26, :185:22, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:52:28, :54:{22,28}]
endmodule

